### ISSUE TITLE
Information:  Advanced Trash Support for SpaceFM Available...

### ISSUE THREAD

**Issue by prodigalgvs** [IgnorantGuru/spacefm#120]
I just wanted to let everyone know that trile7's “trash 0.3.4” bash script, and SpaceFM trash plugin 0.6.2, now supports multiple partitions, as well as removable drives on Ubuntu based distros.  (Thanks dude!)  The script can, of course, be modified for distros other than Ubuntu based.

Trash script 0.3.4 also has the following CLI enhancements that can also be launched from a SpaceFM Custom Command, or an OS panel, Desktop Icon etc.:

trash –empty (empties the “trash-username” folder)
trash –empty-uid (empties the trash-1000 etc. folder)
trash –empty-both (empties both of the above)

Tri did an outstanding job working this out, and I just wanted to let you all know how useful the above script and plugin are, and how much they enhance the already awesome file manager known as SpaceFM!

**Comment by scarlion1** [comment]
No, the way this trashes files on other partitions is improper.  Instead of just moving a trashed file on another partition to that partition's `.Trash-$uid`, this plugin will also "create links to the main trashcan so that all trashed items can be viewed in one place".  That's not standard and will corrupt the listing of other trash cans.  I put [an issue about it in Tri's repository](https://github.com/tri1976/bashscripts/issues/14).
