### ISSUE TITLE
[desktop] Transparent background option

### ISSUE THREAD

**Issue by kanyck** [IgnorantGuru/spacefm#269]
Is it possible to make SpaceFM to draw icons only on a specific desktop, or have transparent background, or both? I use different wallpapers to differentiate compiz desktops (and find it very convenient) but it comes at cost of yielding desktop icons. It would be nice to have both...

**Comment by IgnorantGuru** [comment]
BwackNinja, pulled to next as-is - thanks!

I was wondering why you made it a command-line option rather than a background image style in settings (stretch, etc), which can be changed dynamically.  eg is it not possible to allow the user to change the transparent state once the desktop window is created?  (I don't use transparency so forgive any ignorance.)

eg could I put a "Transparent" checkbox next to the Mode setting in Prefs|Desktop instead of the command-line option?  (I edit those ui files manually these days due to upstream changes so might be better for me to add that if feasible.)

Also some build warnings on this - I try to keep SpaceFM warning free:
~~~~
desktop/desktop-window.c: In function ‘desktop_window_class_init’:
desktop/desktop-window.c:286:22: warning: assignment from incompatible pointer type [enabled by default]
     wc->scroll_event = on_scroll;
                      ^
desktop/desktop-window.c: In function ‘on_realize’:
desktop/desktop-window.c:2547:20: warning: initialization discards ‘const’ qualifier from pointer target type [enabled by default]
     char *wmname = gdk_x11_screen_get_window_manager_name( gtk_widget_get_screen( w ) );
~~~~

**Comment by BwackNinja** [comment]
IgnorantGuru, a lot of setting up the transparent desktop is in desktop_window_new, and thus a new desktop window would need to be created to switch between them. This also meant that I could be sure I wasn't breaking things because the regular codepath was preserved as-is. Plus, I haven't dealt much in the preferences windows and settings infrastructure, so this was also the easiest way.

The on_scroll is an easy fix, GTK2 vs GTK3 ifdef - I had just uncommented what was already there. The lack of const was a careless mistake. I'll fix both of these issues later today.

**Comment by IgnorantGuru** [comment]
BwackNinja, looking it over, I don't see anything in prefdlg that completely destroys and recreates the desktop window, so no precedence for that.  How feasible do you think it would be to set/unset the transparency state in eg desktop_window_set_background, rather than desktop_window_new?  If you know how to do that using the gtk_widget_set_visual, gtk_widget_set_colormap, stick (unstick), etc., then I don't mind refactoring the command line option as a setting - you can just handle the those function calls in desktop_window_set_background.  Anyway you can test ability this in advance?  If it looks good I'll add the setting for you.

I think it would be better as a setting because people will see the feature is there, and its more accessible for testing ,etc.  I do try to keep the CLI brief, but it's okay as it is too.  And it does tend to be an expert feature anyway.

Also, do the background settings (wallpaper, mode) apply if transparency is enabled?  eg do you still show wallpaper in transparent mode, or should we grey those?  Or if we make transparency a setting, can be just list it as an option in Mode and grey the wallpaper?

For the minor fixes like warnings, if you could sync your next branch against mine and work in there, that would probably be easier for me because I'm ahead of your master.  No need for a pull request if you don't want it, you can just note any new commits in your next here.  Thanks.

**Comment by IgnorantGuru** [comment]
To make testing this easy, you might just pretend the Tile setting means transparent (just leave the actual Tile code intact but ignored).  So changing to Tile should activate transparency, and changing to Stretch or any other should deactivate it.  Changing the wallpaper mode automatically runs desktop_window_set_background, so you can just focus on the gtk functions you need.  That will tell us if its feasible.  If you get that working then I can just add a Transparent mode.  See what you think.

**Comment by IgnorantGuru** [comment]
BwackNinja, in the next branch I have removed the command-line option for transparent-desktop and added a wallpaper mode for transparent.  If you turn transparency on or off it pops a message saying that you need to restart the DM.

I didn't touch any of your desktop-window code in making this change, so everything should work as before, but someone please test.

From here we can leave it as-is, offer to restart the DM, or if you can make the code change or destroy/recreate the gtk window without a restart, I can just remove that popup message.

Also, I cleared the one warning, but I don't see how to clear this one:
~~~~
desktop/desktop-window.c: In function ‘desktop_window_class_init’:
desktop/desktop-window.c:286:22: warning: assignment from incompatible pointer type [enabled by default]
     wc->scroll_event = on_scroll;
                      ^
~~~~
Occurs with both GTK 2 and 3.

**Comment by IgnorantGuru** [comment]
Thanks looks good.
