### ISSUE TITLE
[request] Tooltips/Bookmarks Separators/Panel Bar

### ISSUE THREAD

**Issue by Mentha** [IgnorantGuru/spacefm#298]
The possibility to have tooltips in toolbar/sidebar buttons, separators in the bookmarks, I think i can be useful and maybe easy to implement at least the tooltips.

I know that stuff related to the UI is conditioned by themes and distros but in my opinion the Panel Bar could be a little better, it's very intuitive but as i said in my opinion could look more appellative, I'm remembering the nemo right icons for instance, they look very good. Maybe in the status bar the check boxes could look good too. Just saying, this is little details i know don't take me wrong please, i really like SpaceFM. 

Can i create commands to open the panels beside the key shortcuts?

**Comment by IgnorantGuru** [comment]
Not sure why this was never answered, but these have mostly been implemented in the upcoming 1.0.2, currently available for testing in the next branch.

Toolbar items now have tooltips, and bookmarks have separators (since 1.0.1).

Note that the icons in the Panel Bar can be changed by right-clicking on a status bar and selecting Icon.  By default SpaceFM uses only stock GTK icons (for no dependencies), but you are encouraged to change them.  Also feel free to submit any icons you create.

You can open panels via socket commands.  I give an example [here](https://github.com/IgnorantGuru/spacefm/issues/546#issuecomment-107174885).
