### ISSUE TITLE
Memory Use Grows Over Time

### ISSUE THREAD

**Issue by arclance** [IgnorantGuru/spacefm#346]
For a while now I have seen spacefm grow in used memory over time to very high numbers for a file manager.
The highest was ~700 MiB but problems usually occur around ~500 MiB so I rarely let it get that high.
At some random time after memory use reaches over 500 MiB some functions of spacefm stop working.

The two things I am sure stop working are

1. Refreshing (View -> Refresh) a NFS mounted directory.
2. Open with commands for files (nothing happens).

I ran a valgrind memcheck on a debug build of the next branch configured this way
```
CFLAGS='-ggdb3 -O1' STRIP='!strip' ./configure --disable-startup-notification --disable-desktop-integration --with-gtk2
```
The result is here.
https://dl.dropboxusercontent.com/u/69178231/spacefm_valgrind_memcheck_log_2013-05-28.txt

If you want some different debugging tool run on it I can do that if you need it.

**Comment by OmegaPhil** [comment]
@arclance: Please can you try the next branch, it turns out that the standard C runtime's memory management completely fails to release free memory to the OS when 'a decent amount' is unused in SpaceFM's heap - this blew up when huge thumbnails are used in Icon view - I've now put malloc_trim in a few places around the code, which forces the C allocator to do its job (on closing a tab, refreshing a directory, changing directory etc).

The unacceptable memory usage could be this constant heap size increase even when SpaceFM was doing its job freeing things - so now on next the heap should be repeatedly trimmed as you go about your business with the file manager.

**Comment by arclance** [comment]
I will try it but we should let it run for a week to see what happens.
I build with "--disable-startup-notification --disable-desktop-integration --disable-video-thumbnails --with-gtk2" just so you know.

**Comment by OmegaPhil** [comment]
Note that next got a fix yesterday for a memory leak associated with long-running tasks (there is at least one other leak here but we are talking about 10+MB RES wasted when a task runs for an hour...).

**Comment by arclance** [comment]
I reported something like that before (#230).
I will make a new build to test with that fix as well.
From what I saw with the previous build memory use still increases but not as fast (200MiB after 3 days instead of ~4 Hours).

**Comment by IgnorantGuru** [comment]
@OmegaPhil suggested [this fix](https://github.com/IgnorantGuru/spacefm/commit/37a09e931fd4ab9260d194cb506fd19d988025eb) after reviewing the memory behavior while a command task was in progress, with dialog unshown, creating text output to stdout.  That fixed not a leak but an accumulation of the output that wasn't released until the task finished (although in reality it didn't seem to get released at all, perhaps due to fragmentation).

I test no memory growth now while a task is running.  Between that and 04d0e17ef43a0d8e0fcba1035f08562f9a87762a it looks like the memory use has stabilized, and OmegaPhil didn't see any other significant leaks in the memory tools he's using.
