### ISSUE TITLE
video thumbnails

### ISSUE THREAD

**Issue by ItachiSan** [IgnorantGuru/spacefm#384]
*Original Title: [Requests] SMB in-programm + thumbnails support*

Hi,
making this feature request just to know when it wil avaible :)
Also, would help with testing in that case ;P

**Comment by dorkster** [comment]
Hello all. I have experimented with an implementation of this using [ffmpegthumbnailer](https://code.google.com/p/ffmpegthumbnailer/), and have been using it without issue for about 9 months. My branch with relevant changes is here: https://github.com/dorkster/spacefm/tree/video-thumbnails

Some notes:

- The "Max Pic Size To Thumbnail" setting is ignored, since videos are often larger than 32 MiB. So I'm not sure if we want a limit at all for video files.
- Required dependency of libffmpegthumbnailer (duh). I didn't make any of this functionality optional, since I have no reason to turn it off in my own use. But there could be people out there who don't care about video thumbnails and would like to build without an extra dependency.

**Comment by IgnorantGuru** [comment]
Hand branch (see #478) now includes video thumbnail support. This means that to build it, libffmpegthumbnailer-dev must be installed, or use configure option --disable-video-thumbnails

Thanks to dorkster for the ffmpeg code!
