### ISSUE TITLE
/bin/bash

### ISSUE THREAD

**Issue by jagajaga** [IgnorantGuru/spacefm#452]
Hi. Why do you use `/bin/bash`? Why can't you search in path or configure bash's path as launch option? I'm using nixos and don't have `/bin/bash`, I have it somewhere else and can pass the path by compiling, for example. Or wrap the runtime (pass by option as mentioned above)
Show me the lines of use - I will patch.

**Comment by hasufell** [comment]
shouldn't
```
#!/usr/bin/env bash
```
work likewise?

**Comment by hasufell** [comment]
https://github.com/hasufell/spacefm/commit/96c254bd4586ae81fe2746fecdc852b6b0833c2f

can you test this?

**Comment by IgnorantGuru** [comment]
As I said, running bash via $PATH (as in 'env bash') is NOT recommended because you can open root exploits.  Hacking that code is very ill-advised - it has been carefully tested and is used in many dynamic ways, including by root.  If you really want bash located elsewhere, I would suggest adding a configure option to define its full path.

**Comment by jagajaga** [comment]
I need bash located elsewhere. Provide something for to sed in a pre configure phase for /bash/{path/to/my/bash}. That's can be a solution.
But I do respect @hasufell's solution.

**Comment by hasufell** [comment]
I'm not sure I agree that PATH in it's own is a problem.

Besides, NixOS is completely (including the whole package manager concept) based on PATH hackery. If anything, spacefm is not their biggest problem if PATH really opens root exploits.

**Comment by jagajaga** [comment]
I'm definetly sure, that using absolute paths is a bad idea nowadays.

**Comment by IgnorantGuru** [comment]
> I'm not sure I agree that PATH in it's own is a problem.

Well then you should read some of the guides on how to write suid programs, which is effectively what you are doing.  They all advise not to have root execute programs based on $PATH, because experience has shown time and time again that it's very problematic.  It's very easy to open exploits in ways that you wouldn't necessarily foresee and it's best to err on the side of caution.  As udevil is an suid program, I have researched this extensively.  You clearly have not.

That said, it's up to you what you hack, but if you're going to hack SpaceFM that deeply and create root exploits, please distribute it with another name.  Also, I know you know how to add a configure option hasufell, so I'm not sure why you would approach it in such a hackish way.  You seem to be being very careless with your users' security, which is certainly not the philosophy of SpaceFM.

**Comment by IgnorantGuru** [comment]
https://github.com/IgnorantGuru/spacefm/commit/73deed5fa04e432e701dc0151bbc00fa053c988c adds a new configure option --with-bash-path that takes an absolute path to bash v4.  This is currently in the next branch - please test (see README for instructions on installing the next branch).  This is due in 0.9.5 release.

Notes:
* An absolute path must be specified or it will be rejected.  Using any kind of $PATH search to run bash in SpaceFM is likely to create root exploits - this is not guesswork so be forewarned.
* bash v4 features are used by SpaceFM.  Using others shells will create breakage of some features and will void your warranty.
* Every use of bash in SpaceFM will be changed, including in custom scripts and plugins it creates.  This means your custom commands may no longer be portable to other systems without modification.
* On startup, SpaceFM must find the bash program you have specified, or it will refuse to start with an error.
* Currently, the configure scripts alters src/spacefm-auth, which is installed to /usr/bin as part of the SpaceFM program.  This script also contained references to /bin/bash.  This should work okay but is a bit hackish.  It should probably be done in a makefile, but I'm not sure how to do that.
