### ISSUE TITLE
Feature request:: Loading mouse cursor

### ISSUE THREAD

**Issue by orschiro** [IgnorantGuru/spacefm#459]
Hi there,

Is it possible to implement a loading mouse cursor?

For instance, when I access a folder with many files inside, and it takes a couple of seconds to display these files, then it would be handy to have a loading mouse cursor indicating that the files will be displayed.

Currently, without this loading mouse cursor I am never completely sure if the folder is actually empty or still loading the files to display.

Thanks for listening!

**Comment by IgnorantGuru** [comment]
The current book branch ([see testing instructions](https://github.com/IgnorantGuru/spacefm/issues/492)) adds a "Reading..." message to the status bar while the dir is loading.

If this satisfies your issue you can close this request.  As for the mouse cursor, I'm not inclined to add that window-wide due to the multiple panels.  But it's possible to set a busy cursor when the mouse is over a still-loading file list - that would require a few changes.  If you still think that's desirable you can leave this issue open.

**Comment by orschiro** [comment]
> The current book branch (see testing instructions) adds a "Reading..." message to the status bar while the dir is loading.

This is a good idea. Thank you very much!

**Comment by mariusvam** [comment]
Sent from my BlawckBerry 10 smartphone.                                                                                                                                                                                                                From: Robert OrzannaSent: Tuesday, April 28, 2015 1:32 PMTo: IgnorantGuru/spacefmReply To: IgnorantGuru/spacefmSubject: Re: [spacefm] Feature request:: Loading mouse cursor (#459)Closed #459.

—Reply to this email directly or view it on GitHub.
