### ISSUE TITLE
Drop udisks1 support?

### ISSUE THREAD

**Issue by mati75** [IgnorantGuru/spacefm#472]
I forwared Debian bug:

spacefm uses the /org/freedesktop/UDisks D-Bus interface (i.e. udisks1)

Udisks1 is upstream out of support and drop.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=750510

**Comment by IgnorantGuru** [comment]
Thanks but that information is incorrect.  SpaceFM has never used the dbus interface to any version of udisks.  He may think that because he searched the source for "/org/freedesktop/UDisks", but that part of the source is not compiled and was not used to communicate with dbus.

SpaceFM always performs mounting using command-line interface only, using whatever mount tool the user chooses.  If none is chosen it will look for and use (in this order of preference) udevil, pmount, udisks2, or udisks1.  So udisks1 is still supported, but udisks2 is used in preference to it if installed.

Relevant function code for 0.9.4 is at
https://github.com/IgnorantGuru/spacefm/blob/25a2a94bccc5d44770a2a1e227e9127fa761d6d2/src/vfs/vfs-volume-nohal.c#L3232

User's Manual:
http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#devices-settings-mcmd

**Comment by IgnorantGuru** [comment]
Also, really SpaceFM recommends udevil, but that is your choice as the packager ofc.

Certainly no use of dbus here, as SpaceFM has no dbus depends.
