### ISSUE TITLE
Protocol handlers: go-mtpfs issues

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#475]
I've tried to create go-mtpfs handler, analogous to sshfs.
```
echo ">>> go-mtpfs %a"
echo
# Run go-mtpfs through nohup to prevent disconnect on terminal close
gomtpfstmp="$(mktemp --tmpdir spacefm-go-mtpfs-output-XXXXXXXX.tmp)" || exit 1
nohup go-mtpfs "%a" &> "$gomtpfstmp" &
sleep 2s
[[ -e "$gomtpfstmp" ]] && cat "$gomtpfstmp" ; rm -f "$gomtpfstmp"
mountpoint "%a"  # set success status only if positive that mountpoint is mountpoint
```
Key difference is that go-mtpfs process should run all the time while FS is mounted, otherwise 'endpoint not connected'. Therefore I'm forking it to background, then checking if mount is successful by fact.
Here are teh problems:
- If handler is being run in terminal, go-mtpfs exits with terminal despite nohup.
- If handler is not being run in terminal, mount is successful, but:
 - SpaceFM does not open mountpoint on successful mount
 - SpaceFM does not list mount in devices.

**Comment by IgnorantGuru** [comment]
Thanks.  On terminal is close causes exit, I don't necessarily have a solution for that.  I consider such behavior a bug.  sshfs behaves similarly, but in the method I use in the new default sshfs handler, I was able to close the terminal.  Otherwise you may need to leave it open or report the issue to go-mtpfs.

The main problem is the device not being detected.  Please provide the relevant lines for the device from these files:
/proc/self/mountinfo
and /proc/mounts or /etc/mtab

And also be sure you have tried Show|Internal Devices, and other Show settings that may affect it.

Also, if running spacefm in a terminal, note any output when the mount occurs.

**Comment by IgnorantGuru** [comment]
Noting #138

**Comment by Vladimir-csp** [comment]
/proc/self/mountinfo
```
99 39 0:34 / /home/psycho/.cache/spacefm/go-mtpfs- rw,nosuid,nodev,relatime shared:83 - fuse.DeviceFs(GT-I9192) DeviceFs(GT-I9192) rw,user_id=1000,group_id=100
```
/proc/mounts
```
DeviceFs(GT-I9192) /home/psycho/.cache/spacefm/go-mtpfs- fuse.DeviceFs(GT-I9192) rw,nosuid,nodev,relatime,user_id=1000,group_id=100 0 0
```
/etc/mtab
```
DeviceFs(GT-I9192) /home/psycho/.cache/spacefm/go-mtpfs- fuse.DeviceFs(GT-I9192) rw,nosuid,nodev,relatime,user_id=1000,group_id=100 0 0
```
Tried enabling everything in devices menu, still not showing this mount.

Also note trailing dash in mountpoint path. Mountpoint name generator should be tweaked to throw the dash out for targetless filesystems.

**Comment by Vladimir-csp** [comment]
Tried jmtpfs. It works fine without any nohup and redirect tricks, both in terminal and not.
This should be fine for handler:
```
jmtpfs "%a"
mountpoint "%a"  # set success status only if positive that mountpoint is mountpoint
```
even check can be removed.

But yet again, SpaceFM does not show or open the mount. And mountpoint has a trailing dash.
```
jmtpfs on /home/psycho/.cache/spacefm/jmtpfs- type fuse.jmtpfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=100)
```

**Comment by IgnorantGuru** [comment]
Above issues should be corrected in https://github.com/IgnorantGuru/spacefm/commit/f19f1786438e03e632c597447a458cee559c90c1

I think the dir will auto-open now that the device should be detected.  (Nice of go-mtpfs to put parentheses in the fstype!  Let me know if that interferes anywhere.)  I added jmptfs as as default mtp handler - click All Defaults to add it.

Also see this new note in manual:
*Note: The whitelist mtab_fs= property also may affect what mounted protocols SpaceFM detects and lists in its devices list. By default, SpaceFM will list all filesystems mounted to a SpaceFM .cache directory (the default location for %a auto-created mount points - see below), and it will list mtab filesystems that begin with "fuse.". To have it detect and list another filesystem in the devices list, add the type with mtab_fs=FSTYPE to a protocol handler's whitelist.*

**Comment by Vladimir-csp** [comment]
...tested jmtpfs. It detects and opens it, ok.
But when trying to unmount, it tries to use udevil, despite that I've placed jmtpfs handler above udevil. And even when udevil handler is disabled.

I do not think that jmtpfs should be default for mtp. There also exists mtpfs, which works for another set of devices. Unfortunately, I do not have such device to test. mtpfs, jmtpfs, go-mtpfs should all have their own handlers.

I will continue testing...

**Comment by IgnorantGuru** [comment]
The new udevil default whitelist is "ftp http https nfs smb ssh mtab_fs=fuse.sshfs" rather than "ftp http https nfs smb ssh mtab_fs=fuse.*", which may correct your issue.  But if you have "mtab_fs=fuse.jmtpfs" in your whitelist and it comes before others, that unmount command should be used.  Check the terminal output to see why a handler is chosen - used parts of whitelist will be in square brackets [ ] per the manual.

For now jmtpfs is the default for the mtp:// protocol handler.  If someone wants to provide another I'll consider it.  I don't use any of them.  Thanks for testing.

**Comment by IgnorantGuru** [comment]
Actually it may be using udevil because it's not recognizing the device as a mounted protocol (doesn't see a URL).  In that case we may need to add a device handler to unmount jmtpfs.  I'll look over how that's handled in general.

**Comment by IgnorantGuru** [comment]
Yeah I think a device handler was being used.  Now if a non-block device is not identified as a network, if it has a protocol handler based on mtab_fs then that will be used for unmount and properties, rather than a device handler.

In the updated manual:
*Note: The whitelist mtab_fs= property also may affect what mounted protocols SpaceFM detects and lists in its Devices list.  By default, SpaceFM will list all filesystems mounted to a SpaceFM .cache directory (the default location for %a auto-created mount points - see below), and it will list mtab filesystems that begin with "fuse.".  To have it detect and list another filesystem in the devices list, add the type with mtab_fs=FSTYPE to a protocol handler's whitelist.  This will also ensure that your protocol handler, rather than a device handler, is used to unmount and show properties for the mounted protocol.*

**Comment by Vladimir-csp** [comment]
ok, jmptfs mounts and unmounts successfully, go-mtpfs mounts and unmounts successfully (if not in terminal)
Terminal should not be needed for targetless filesystems. Although, I do not know what can happen when multiple mtp devices are connected.
Will try to test that when I get the chance.
