### ISSUE TITLE
Handlers: UI Add Apply and Close buttons

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#476]
Here is my IMHO:
"Add" button should create an empty form with "New Handler" in name field
"Apply" should be renamed to "Save" and relocated under the form.
When leaving unsaved form, UI should warn and ask to save.

**Comment by IgnorantGuru** [comment]
I've been pondering this and input is welcome.  For now it works identically to the Context page of custom items.  This UI is designed for fast use after you get to know it, rather than being slow and interactive, popping messages for you to read.  It is loosely modeled after Claws Mail's filters config.

To use the Add button in the way you mean, Ctrl-Click on the selected handler to unselect it.  The Add button works as it does so you can copy a handler.

I think Apply's location is better, since putting it next to Defaults or Close could be bad if the next-door button is accidentally clicked.  We're considering adding a "Close*" asterisk label to the close button if there are changes.

**Comment by Vladimir-csp** [comment]
You could add "Copy" button. It would be just as fast (or even faster, no need to ctrl+click before "Add")
And "Add" button would create handler filled with default comments about what scripts should do.
The only pop-up would be about unsaved handler - and it can be avoided by properly saving before closing.
"Apply" just feels out of place IMHO. It logically belongs to the content, not to the list.

Anyway, handler editor is not a tool anyone would use every minute, crunching hundreds of handlers at a pace.

**Comment by IgnorantGuru** [comment]
I have changed the Close button to a Cancel button, and added an OK button which presses Apply for you.  Also, the Apply button now changes sensitivity.  It's not perfect but I think this is more effective.

Also, only if the script has changed in the textview will it be saved, so as not to conflict with external editor.

**Comment by Vladimir-csp** [comment]
Why do you prefer Apply button under the list?
If you have OK and Cancel buttons that close the entire UI, then it is implied that changes are saved or dropped through entire UI. But If you edit a handler and then switch to another handler, the first handler just silently drops changes. OK and Cancel affect only current handler, but close the entire handler editor.

**Comment by IgnorantGuru** [comment]
My logic here is that OK, Apply, Cancel have certain typical behavior, where Apply applies the changes but keeps the window open, and OK applies the changes and closes the window.  Cancel discards unapplied changes.  I think Apply placed under the list works well - only really used if changing handlers in the list.  This also matches the custom command Context dialog layout.

I considered a message before switching to another handler unapplied, but there were some issues implementing that with the way the list is done (click event, etc).  So for now it will just silently drop unapplied changes, but the Apply button does become sensitive to remind.  And I do prefer non-interactive overall.

Only other thing I'm considering is a prompt when pressing Remove ("Really delete the selected handler and all associated scripts?")

**Comment by IgnorantGuru** [comment]
afe93cc adds the prompt to apply changes when switching to another handler, and also prompts on remove.  Testing is appreciated.
