### ISSUE TITLE
Seperate Desktop/Panel/Pane Icon Sizes

### ISSUE THREAD

**Issue by maximstewart** [IgnorantGuru/spacefm#480]
Would you please look into adding a seperate icon size setting field for the Desktop and each file manager Panel? It would be a great enhancement or feature!!

**Comment by Vladimir-csp** [comment]
Given the new changes to thumbnail sizes, I think these separate size controls would be right:
- Main pane (icon mode)
- Main pane (list and table mode)
- Toolbars
- Side panes
- Desktop

Current "Large icons"/"Small icons" may be confusing anyway.

**Comment by IgnorantGuru** [comment]
I can see the usefulness of these, but as noted elsewhere, these changes would not be as simple as adding the settings, because the code is not designed for it.  eg icons are loaded and cached with object refs used, and if different panes are using different sizes, multiple sizes may need to be cached.  And the code that loads the icons would need to be pane/panel-aware, etc.  Currently all the code uses only 3 icon sizes (small, large, and toolbar), and this would require a dozen or more sizes to be stored and acted on.

First step would be some research to see what is affected in the code, and how the icon cache/references are implemented.

**Comment by IgnorantGuru** [comment]
Also noting #94 wrt this.

**Comment by RaveYoda** [comment]
Ahhh, gotcha, that makes since. I wish I could code better as I would love to tackle this for you. XD But my skill set is at zenity/bash level at this time. =/ Though I'm working to learn python/gtkbuilder. I figure once I'm more comfertable with those two transitioning to C/C++/gtkbuilder would be easyer. I would apreciate any insight as to how you began coding and where I may start to get to your level because helping out would be awesome! PS- Should I close this or keep it open for you?

**Comment by IgnorantGuru** [comment]
Yes please leave this open - some of it can be considered.  I was just explaining that it's not a simple change and would require research and redesign.  iirc SpaceFM caches up to two icon sizes for each mime type on demand.  Then when it needs an icon in the file lists or on the desktop, it just adds a reference to these cached objects.  So having too many different sizes wouldn't be easy and would affect speed and memory use.  The current design provides two customizable sizes for use: large and small.

I just added a 'Large Icons' option to the hand branch as detailed [here](https://github.com/IgnorantGuru/spacefm/issues/478#issuecomment-89901645).  That should help with changing icon sizes on the fly from small to large in those views.

As for the desktop, the cache issue is the main reason for the desktop sharing the same large icon size.  The prospect of a separate setting would require research before I could comment on how feasible it is.

Sorry I don't have any coding advice - I learned C long ago (in a galaxy far away), and I learned GTK by writing SpaceFM.  As far as working on SpaceFM, I don't accept a lot of contributions, unless it's a small thing, because it's a lot of work to integrate and review code contributions and maintain stability.  SpaceFM is a prototype which was built from another program (PCManFM 0.5, before it went to gvfs), so the code is a bit difficult to work with.  I don't recommend trying unless you're very determined.  Working on this would not be a good way to learn anything.  ;)

**Comment by IgnorantGuru** [comment]
Actually since there are relatively few icons on the desktop (compared to dirs containing thousands of files), it might be feasible to skip the cache and just load the icons.   GTK usually has an icon cache running too.  So the seperate setting for desktop icon sizes might be feasible.  Would probably just be a matter of changing the icon loading functions.  Just noting this.

**Comment by Vladimir-csp** [comment]
> since there are relatively few icons on the desktop (compared to dirs containing thousands of files)

Never underestimate some users` bright talent at shitting all over their destkops :) And size of desktop is not the limit...

**Comment by RaveYoda** [comment]
Aight, thanks for the advice!! And I must agree with @Vladimir-csp on his point. My mother put well over 200 files/folders on her desktop. T.T Made me cringe every time I saw that mess. She moved to a Note3 and has kept it clean so far. <fingers crossed> Also, on the average i'd bet it'd work fine to use the GTK cache with a seperate video icon cache as you mentioned to handel the desktop icon sizes. That would largly address my preferences/needs as well since i'm not looking to change the icon size indavidually in each pane but the sizes for the desktop seperae from the file managers'.

**Comment by RaveYoda** [comment]
An addendum to my last reply, by using a larger "Small Icons" setting,96x96, and using a smaller "Large Icons" setting,64x64, allows for what i'm aiming for. That and coupling it by changing my view type in the file manager to compact rather than icon allows me to have small desktop icons with larger file manager icons. Though, having the text to the right is somewhat not my preference.XD Still, untill there is a change in the code it is closer to what i'm gunning for. =]

**Comment by IgnorantGuru** [comment]
Noting #396

**Comment by ghost** [comment]
Closed since this isn't being maintained by @IgnorantGuru

**Comment by ryanmusante** [comment]
Sadness. Where art thou, @ignorantguru?

**Comment by ghost** [comment]
@ryanmusante Doing other stuff I assume. I think someone else took over but don't recall.
