### ISSUE TITLE
Secure mode

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#481]
Please consider the mode in which any function that involves scripts is only accessible if scripts are root protected (and located in /etc/spacefm). That includes handlers and custom actions.
Such mode could be activated in settings with password prompt to relocate scripts and actions to global config dir. 
This setting would be global, and disabling it would also require password.

**Comment by IgnorantGuru** [comment]
This is well outside of the current security model, but I will clarify it for you and others and maybe note this in the manual Handlers section.

All the customizable handlers and scripts within SpaceFM, when SpaceFM itself is run as a non-root user, should not execute root commands, even via su.  As a rule of thumb, anytime a file is executed as root, or executes something as root via a su password prompt, it should be owned and writable only by root.  Otherwise you open potential priviledge escalation and other exploit vectors.  Since SpaceFM's scripts, handlers, and custom commands are user-owned and changeable by the user, they should not do anything as root for strict security.

The exception to this in SpaceFM are the plugins menu, the contents of which are root-secured, and a few root commands in the Devices' Root menu.  In that case, the command is saved as root, and it is shown to you everytime before it is run.  Further, there are built-in root functions that are part of SpaceFM's code, such as renaming a file as root, and these are safe to use.

So if you want to do a custom thing as root, in general you'll want to create a custom command and install it as a plugin, which will protect it.  Plugins can easily be made to operate on the current selected device and other browser context.

As for handlers, these are designed to use user-mountable filesystems such as fuse or via udevil.  udevil (suid) can be configured to handle most block device filesystems, and fuse handles most filesystems, so in general the user should not need to be running handler commands as root.  That is a poor approach to security.

While your model may sound attractive, having users write scripts that are executed by root is not a good idea.  It's very easy to open exploits writing root scripts.  A much better approach is to use a hardened program like udevil which greatly limits what can be done, and highly limits the interface exposed to the non-root user by design.  Making a large GTK app handle extensive security in this area is not nearly as secure as a very small program like udevil (which also immediately drops its root privs and runs almost all its code non-root until it is ready to run mount).  Mostly SpaceFM just runs a few limited commands as root, which is different than running complex user-written scripts.

**Comment by Vladimir-csp** [comment]
I didn`t propose running handlers as root. I meant... well first, extend the same feature of root protection of plugins to handlers. So user could  place scripts into global config and refuse of write permissions.
And second, ability to lock evrything down, make every customisation global and disable further user customization. All scripts should of course be run as user.

**Comment by IgnorantGuru** [comment]
If you're not running root commands, there isn't a lot gained by protecting the user files as root.  No priviledge escalation.  Anything the intruder can do by changing your files they can probably just do directly.  Once someone gets into a user-level account on Linux, they can seriously disrupt your entire UI - aside from the system files and other user accounts, you're owned.  This is more a limitation of Linux's design, so you might try a system-level solution like selinux or maybe sandfox.  Yet since SpaceFM by its nature of being a file manager requires extensive system access, your real results may be limited.

You could also run git as root on your SpaceFM config directory to track changes.  This also allows you to roll your config back.

Also, it is possible to copy your SpaceFM config dir to a root-owned tree and make it root-owned and read-only.  You can then start SpaceFM with that config dir and you will be able to make UI changes, but they won't be saved.  It should run okay, just limits the nature of SpaceFM always growing with your uses, becoming a customized FM, of course.  You could even make a plugin which performs this locking and unlocking as root.  But the config directory must be in a root-owned tree, and even the shortcut or desktop file you use to run SpaceFM may represent an intrusion vector if it is user-writable, as does the very environment you're running SpaceFM from.  A process could even watch your directory in the kernel and modify it the instant it became user-writable.  Root exploit vectors get very tricky.  But in terms of some security-through-obscurity, you might gain a little.

Overall it sounds like a job for an selinux or sandboxing type of thing.
