### ISSUE TITLE
Protocol Handlers

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#482]
Here I will publish a polished list of my handlers that work and tested:
jmtpfs, go-mtpfs, mtpfs, simple-mtpfs, gphotofs. List may change.

**Comment by Vladimir-csp** [comment]
### gphotofs:
terminal=false
whitelist:
```
gphotofs mtab_fs=fuse.gphotofs
```
mount:
```
gphotofs "%a"
```
Unmount:
```
fusermount -u "%a"
```

### simple-mtpfs
terminal=false
whitelist:
```
simple-mtpfs mtab_fs=fuse.simple-mtpfs
```
mount:
```
simple-mtpfs "%a"
```
umount:
```
fusermount -u "%a"
```

### jmtpfs:
terminal=false
whitelist:
```
jmtpfs mtab_fs=fuse.jmtpfs
```
mount:
```
jmtpfs "%a"
```
unmount:
```
fusermount -u "%a"
```

### go-mtpfs
terminal=false
whitelist:
```
go-mtpfs mtab_fs=fuse.DeviceFs(*
```
mount
```
# Run go-mtpfs in background, as it does not exit after mount
outputtmp="$(mktemp --tmpdir spacefm-go-mtpfs-output-XXXXXXXX.tmp)" || exit 1
go-mtpfs "%a" &> "$outputtmp" &
sleep 2s
[[ -e "$outputtmp" ]] && cat "$outputtmp" ; rm -f "$outputtmp"
# set success status only if positive that mountpoint is mountpoint
mountpoint "%a"
```
unmount:
```
fusermount -u "%a"
```

### mtpfs:
terminal=false
whitelist:
```
mtpfs mtab_fs=fuse.mtpfs
```
mount:
```
mtpfs "%a"
```
unmount:
```
fusermount -u "%a"
```

### udevil:
terminal=true
in terminal for network fs with passwords no changes beyond that.

**Comment by Vladimir-csp** [comment]
added fusesmb and smbnetfs (may require polishing - options, terminal for passwords)

**Comment by IgnorantGuru** [comment]
Thanks for these.

In the whitelist, rather than the fs, list the protocol.  For example "mtp://" would be "mtp" in the whitelist.  For mtp probably one default solution will do, so I used jmtpfs, which seems to have positive reports.  I don't use this so any other ideas welcome.  Or maybe a handler which uses whatever is available, like my Mount ISO file handler that uses udevil or fuseiso.  Same for unmounting.  Or I could include separate handlers and the user can reorder them, if that's really necessary to have more than one.

For smb, I'm still using udevil as the first default, but I included fusesmb below it.  Doesn't look like the fusesmb handler will accept usernames/passwords/ports? in the URL as-is.  Not sure why we would need both fusesmb and smbnetfs for the same smb:// protocol?

And I added gphoto as "gphoto://" ("gphoto in the whitelist rather than gphotofs)

**Comment by Vladimir-csp** [comment]
It is not all so straightforward with MTP variants. Jmtpfs periodically messes with text file encodings for me, and I suspect it somehow throws bits out of files. 
The most horribly written go-mtpfs produced the best results for android phones.
I do not know which of them is suitable for classic MTP devices, like dumb pre-android music players, as the only such player I can access, just siletnly uses UMS, despite explicit MTP setting.

Fusesmb and smbnetfs are targetless. They mount the whole browseable smb network tree and both require their config files for authentication (insecure). Fusesmb feels faster, smbnetfs hangs on i/o here and there. They both should not be default.

What if we include two protocols for each  handler, generic and specific, like ```mtp go-mtp```?
So accessing ```mtp://``` would pick first supported handler, and accessing ```go-mtp://``` would pick go-mtpfs handler?

**Comment by Vladimir-csp** [comment]
- added ifuse
- reordered mtp handlers
- added mtp and specific protocols to mtp handlers

**Comment by Vladimir-csp** [comment]
updated smb-udevil handler to open mountpoint after successful mount

**Comment by IgnorantGuru** [comment]
Thanks I have updated those, and I wrote the mtp handler to use whatever is installed.  Only one no used is smbnetfs (I figure if someone wants to use that instead of udevil or fusesmb, they can change the command).  udevil is still used first on smb because it can handle password, etc. in the URL.

**Comment by IgnorantGuru** [comment]
Additional handlers may now be added to the [Plugins Wiki](https://github.com/IgnorantGuru/spacefm/wiki/plugins).  Feel free to drop a note here or elsewhere letting me know if you've added one, and I'll consider adding it to the default set.  Thanks for contributing.
