### ISSUE TITLE
[GTK3] Crash when selecting and unselecting items

### ISSUE THREAD

**Issue by mm-d** [IgnorantGuru/spacefm#485]
System: spacefm 0.9.4 on Gentoo
If a window has only few items and I select items by dragging with my mouse (starting from empty area) and unselecting them, spacefm crashes when I would have unselected all items. When launching from terminal I got:

**
Gtk:ERROR:/tmp/portage/x11-libs/gtk+-3.14.9/work/gtk+-3.14.9/gtk/gtkrbtree.c:914:_gtk_rbtree_node_find_offset: assertion failed: (node)
zsh: abort      spacefm

**Comment by IgnorantGuru** [comment]
This sounds like it may be caused by a GTK3 theme which has not been updated for your current version of GTK3 (they keep breaking themes with almost every GTK3 update).  You might try the default Adwaita theme as a test.

If the problem persists with the Adwaita theme, please submit a full backtrace via the BUILD DEBUG instructions in README.  Thanks.

**Comment by IgnorantGuru** [comment]
Closed for inactivity - feel free to add more info below and this issue can be reopened if needed.

**Comment by Klick3R** [comment]
Ok, noticed there was a "need info" request on this subject, i have the same crash from the same action, but slightly different message, i have tried several gtk themes, done full system update.
im using archbang with default openbox.
im not familiar with doing a backtrace, but ill have a look at it and i will report back when i got it.
This is the message i get when crashing:
Gtk:ERROR:gtkrbtree.c:914:_gtk_rbtree_node_find_offset: assertion failed: (node)
Aborted (core dumped)

**Comment by IgnorantGuru** [comment]
@Klick3R Thanks for the info.  Please include the following:

* GTK version
* List view style (Detailed, Icon, Compact)
* Result of testing GTK3 with Adwaita theme or GTK2 with no theme (or with default Gnome theme).  Testing with other 3rd party themes is not helpful because they may have the same bug (which can be inherited when themes are copied and changed.)

**Comment by Klick3R** [comment]
Ok so this is what i'we come up with: i got 2 gtk versions, not sure which one the spacefm uses, if you have any tips on checking that out ill have a close look at it.
gtk2 2.24.28-1
gtk3 3.16.3-2

And i made sure its using Adwaita.
and i also made sure to check the different list views, and came up with that its only the "detailed" view that crashes when selecting all and deselecting without letting go of the mouse, the two other views work as they should.
Hope this helps, need any more info just ask and ill try getting it.

**Comment by IgnorantGuru** [comment]
Thanks for the info.  You can always see what major version of GTK SpaceFM is using by running:

    spacefm --version

In GTK3, Detailed list view, I have to enable View|Style|Rubberband Select to be able to select multiple files.  Then if I click on a file date and drag, the rubberband selects several files.  Then if I reduce the rubberband until no files are selected, I still don't see a crash.  Is that how you are selecting and unselecting the files?

If I click and drag on a filename, the last file is never unselected.  I have to start from the file date or other column.  (The OP says "starting from empty area", but I can't select if I start from below the listed files.  ???)

I'm using GTK 3.14.

Unfortunately the backtrace isn't very useful - looks like GTK3 is crashing in libc.  You don't  have the debugging symbols installed for libc or GTK, but I'm not sure that would help much anyway.

**Comment by Klick3R** [comment]
ok so i decided to make a short video of how and what happens: 
http://tinypic.com/r/2jg409j/8

it actually starts marking but is not noticeable until just before actually hitting the first row. 
I also tried looking for the libc and gtk symbols for dbg but could not find any in the arch repo or aur repo.

**Comment by OmegaPhil** [comment]
I also get this following the posted video, full backtrace for all threads: https://gist.github.com/OmegaPhil/073aee819ec4a8c58d0e

Up to date Debian Testing install here with libgtk-3-0 at v3.14.5-1.

**Comment by IgnorantGuru** [comment]
Looks like it might be originating at [line 628 in exo-tree-view.c](https://github.com/IgnorantGuru/spacefm/blob/next/src/exo/exo-tree-view.c#L628):

    return (*GTK_WIDGET_CLASS (exo_tree_view_parent_class)->motion_notify_event) (widget, event);

Perhaps it should validate exo_tree_view_parent_class is non-NULL before referencing motion_notify_event?

Or in another thread, or just due to timing, maybe there is a race condition with the parent class becoming invalid before or during this function?

**Comment by IgnorantGuru** [comment]
@OmegaPhil Might help if you install gdb symbols for gtk3 and glib?  Seems to be crashing fairly deep in the gtktreeview motion-notify event handler afaict.  What it's doing in there might give a clue.

**Comment by OmegaPhil** [comment]
For what its worth, I've updated my gist backtrace with symbols now.

**Comment by OmegaPhil** [comment]
Right, finally got some time with this - basically in GTK2 you have to have a selected item in order to start a rubberband select - in GTK3 you don't, so in 2 you can't drop the selected item as part of fiddling with the rubberband area, but in 3 you can start it below any item, move to select the item, then move down to unselect - and suddenly GTK3 chokes on the new possibility.

I don't yet know anything about how the rubberband code works, but I think the solution would be to prevent a rubberband select starting without an item selected, @IgnorantGuru, should I go ahead with this? There are other assertation failures just dragging around the empty space that also need addressing.

**Comment by IgnorantGuru** [comment]
@OmegaPhil Yeah, please - anything you can throw in there to catch that.  I think most of the rubberbanding is GTK internal, but there are some events.  Let me know if you don't see what you're looking for.  All of that mouse code is a bit tricky so good to proceed carefully and test various modes when done (Detailed, Icon, Compact, and Single-click with/out hover, etc.)

Also, I don't think GTK 3.0 allows selection below any item - they seem to have introduced it in one of the more recent GTK3 versions.

**Comment by OmegaPhil** [comment]
Next has now been updated with a fix - basically I've formalised the GTK2 behaviour of no rubberband selection from nothing - this only affects the detailed view BTW.

Please test to confirm, currently Works For Me™

**Comment by OmegaPhil** [comment]
Can't seem to trigger any further non-fatal asserts anymore, so I'm assuming this is all fixed for now.
