### ISSUE TITLE
No choice of views in View menu or anywhere else.

### ISSUE THREAD

**Issue by prodigalgvs** [IgnorantGuru/spacefm#495]
Thank you for version 1.00.  

I do not have any Compact, Details, Or list views under the view menu.  Nor can I find any reference to them.

Xubuntu 14.04.2.

**Comment by IgnorantGuru** [comment]
The View menu containing them is the panel one.  Right-click on a file in the file list and select View|Style.

Per-panel settings are in the file list's View menu, while mostly program-wide settings are in the main menu bar's View menu.

**Comment by IgnorantGuru** [comment]
Also if you show which documentation confused you maybe it can be improved.

**Comment by prodigalgvs** [comment]
Very diplomatic :)  I did look, and read that.  I guess it did not sink
in.  My bad.

Also, the "spacefm-gtk3_1.0.0-1_all.deb" file from Sourceforge gives a
"Error: Conflicts with the installed package 'spacefm-common'" message
even after the new version is installed.

Gordon VS
gvscheik1@cciwireless.ca

**Comment by IgnorantGuru** [comment]
1.0.0 is already in [Debian testing](https://packages.debian.org/sid/spacefm), but due to the upcoming jessie release I'm not sure what's frozen.  Best to use their packages if you can, which is where that spacefm-common comes from.

If you want to use my deb packages, which are mostly intended for older versions of Debian, you'll need to remove the others, including spacefm-common.
