### ISSUE TITLE
[book] Working dir for applications

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#498]
There should be an option to ignore current dir when launching applications from bookmarks. 
A switch in context of the item with two states:
- use current dir as working dir
- use Path= from application`s .desktop file or $HOME if there is no Path.

**Comment by IgnorantGuru** [comment]
> There should be an option to ignore current dir when launching applications from bookmarks. 

Why?

Launching them from Bookmarks should currently behave the same as launching them from the Open context menu.  I think starting them in the current dir is typical fm behavior.  Path= might be reasonable to obey - I'll take a look, though I question whether it has much practical use.   For other desired behavior a custom command may be more appropriate than an application shortcut.

**Comment by IgnorantGuru** [comment]
In my tests with the book branch, both applications in the Open context menu and application bookmarks behave the same:  they start the application in the current directory, unless Path=DIR is included in the .desktop file, in which case they start in DIR.

This behavior looks correct and no plans to change it.  If you want an application to have a custom working dir, you can use Path= or use a custom command to start it, rather than an application bookmark.
