### ISSUE TITLE
[book] bookmark is created for parent dir

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#499]
When you select file or directory and create a bookmark via it`s context menu Create>Bookmark, current (parent to the selected item) directory goes to bookmark.

**Comment by IgnorantGuru** [comment]
If a single file or dir is selected, the [book branch](https://github.com/IgnorantGuru/spacefm/issues/492) will now bookmark it via (file list context menu)|New|Bookmark.  Note that any key shortcut to this item will bookmark the current directory only.  From the updated manual:

<blockquote><p>To add a new bookmark targeting the current directory, select New Bookmark from the Bookmarks menu (a key shortcut may also be assigned to this item - right-click on it to set one), or right-click in the Bookmarks pane or menu and select <a href="#designmode-designmenu-bookmark">New|Bookmark</a> (which will ask you to select a directory target).

<p>To bookmark a single selected file or directory, or otherwise the current directory, right-click on the file list and select New|Bookmark.

<p>To bookmark a mounted URL, in some cases you can right-click on the URL in the <a href="#devices-list">Devices List</a> and select Bookmark.  Or, a URL or file/dir path in the Path Bar may be bookmarked by right-clicking on the Path Bar and selecting New Bookmark.
</blockquote>
