### ISSUE TITLE
Issue resulting from switching from Icon View back to Detailed View,

### ISSUE THREAD

**Issue by prodigalgvs** [IgnorantGuru/spacefm#507]
Switching from Icon View back to Detailed View can result in the Names column being partially hidden behind sidbar.  No horizontal scrollbar shows.  Problem is fixed by clicking on a bookmark to another folder.

This is not every time, but occurs regularly (several times per day).  It was also an issue under 0.9.4.1.  See attached
![screenshot](https://cloud.githubusercontent.com/assets/1977807/7291746/8a8e3a9a-e951-11e4-8633-d9775ddf6fa7.jpg)
 screenshot.

**Comment by IgnorantGuru** [comment]
Thanks but this is likely an issue caused by a malfunctioning GTK theme.  Test with the Adwaita theme to verify the 3rd party theme as the cause, and also run SpaceFM from a terminal to see any theme-related warnings.  If the problem persists with Adwaita, be sure to include the output of <code>spacefm --version</code> in your report.

**Comment by prodigalgvs** [comment]
It happens across all themes.

Gordon VS
gvscheik1@cciwireless.ca

**Comment by IgnorantGuru** [comment]
Not reproducible.
