### ISSUE TITLE
thumbnail refresh timeout

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#508]
I started copying a video file from network resource to local directory, while it copied, the thumbnail was in constant update/flicker. I think there should be some timeout for thumbnail refresh of constantly changing files.

**Comment by IgnorantGuru** [comment]
Nothing new here - SpaceFM rebuilds any thumbnail (video or image) when a file changes.  File changes are cached and handled every half second or so, so the thumbnail will keep being regenerated.

For network filesystems, if you include the type in Devices|Settings|Change Detection, it shouldn't load thumbnails at all.  So I assume in this case you're using a network filesystem but allowing change detection.

Any impact on performance or is this merely a visual issue?

This should probably be improved for any kind of fs.  Maybe a timestamp on the thumbnail, or maybe it can read the file timestamp from the thumbnail cache, and not update more than once every 5 or 10 seconds.

**Comment by Vladimir-csp** [comment]
It`s on local FS, not the issue of blacklist. I haven`t measured performance hit, I doubt that it made a dent on Core i5 machine, but such constant update is unnecessary. 
IMHO, the best way is to read  file timestamp from the thumbnail cache and make a longer pause after each consequential update. Maximum pause - 5 secons, reset pause to zero after 10 seconds without update. Something like that.

**Comment by IgnorantGuru** [comment]
Well that would require data for each thumbnail, recording it's state.  The point of using the file timestamp is so I don't need to add any memory usage or data structures (for thousands of files).  Also, the file changes are handled in a separate thread from the thumbnail loading code.  I'll have to look over the code to see what is feasible.

**Comment by IgnorantGuru** [comment]
This is not simple, because the one notification thread destroys the thumbnail when the file changes, then elsewhere it is recreated.  Even if the old thumbnail file is reused, it will still unload and reload it, causing a flash.

What I have done for now is make it so if mod time of video being thumbnailed is less than 5 sec ago, it doesn't show any thumbnail.  While a file is being copied or downloaded, it's mod time will be new, so it won't show a thumbnail.  When the copy completes, the mod time is set to the time of the original file, so this will trigger a thumbnail to be loaded at the end.

However, if a new file is saved and closed (for example when downloading a file), it's mod time will be new and so it won't show a thumbnail, even when the download completes.  You'll have to manually Refresh to load it (allowing 5 seconds to pass since the file last changed).

What do you think, is this better than flashing?  In one sense, the flashing could be seen as an indicator that a copy is in progress.  Otoh it's distracting.

I'll leave this change in next for now so we can try it.  To really change how this works would require substantial redesign.  I may also revisit this area when I do some other work coming up, so I'll keep it in mind.

**Comment by Vladimir-csp** [comment]
I'm not opposed to flashing as it is. It's just frequent reading and processing is pointless.
This solution is fine. As for new files, would it be troublesome to somehow 'mark' recent file to schedule an auto-check for it's mtime after five seconds?

**Comment by IgnorantGuru** [comment]
I think I have fixed this - please test the alpha branch.

What it does is it now keeps a separate queue for changing video files if thumbnails are enabled and SpaceFM is built with ffmpeg.  This queue is processed after 3 seconds providing no video files in that dir change in that period, otherwise the timer is reset.

So when copying or downloading a video file, you should see the file size updating at the normal rate, but the thumbnail will only be loaded when the file is initially created (if possible, otherwise icon shown).  Then it won't be updated again until 3 seconds after the last write to the file.  Or anytime there is a file writing pause greater than 3 seconds, it will be updated then also.

**Comment by IgnorantGuru** [comment]
Actually, try the next branch, which now has the same code, but reduces the delay to 1 second, and also works the same for images (to address #591).

**Comment by IgnorantGuru** [comment]
Also, I have made it flush the delayed queue every 7 seconds or so.  Otherwise when downloading or copying multiple files, no thumbnails would be shown until they all completed.  This way it will attempt to load the thumbnail every few seconds anyway, which is light cpu usage.  And often it will be able to show a thumbnail before the file completes.

**Comment by IgnorantGuru** [comment]
Please note the latest code for testing this is once again in the alpha branch, not next, [as explained](https://github.com/IgnorantGuru/spacefm/issues/582#issuecomment-159708250).
