### ISSUE TITLE
Request:  Reduce padding above and below new toolbar buttons

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#531]
No big deal, but could the padding above and below the buttons on the new toolbars be reduced?  As it stands it looks as if the padding is 50% of the button size for both top and bottom of buttons.  This makes for a large toolbar with smallish looking buttons.  I have tried Adwaita and other themes and they all could improve visually with less padding.

**Comment by IgnorantGuru** [comment]
This morning in 80dcd09d I made a change which may reduce the padding.  Beyond that, there isn't any padding added, except for the theme, which will vary.  Depending on the font size used in the pathbar, the height of the pathbar may force the toolbar to be vertically larger.  Also note that you can set the toolbar icon size in Preferences.

GTK3 tends to be very wasteful with padding - you might try a thinner theme with it.

If that doesn't help, please include your GTK version and a screenshot of the toolbars so we can compare what you're seeing.

**Comment by IgnorantGuru** [comment]
As I noted in #519:
Actually I did find a way to crunch the GTK2 toolbar down using a size request on the buttons, to the point where the icons are on top of each other.  In  fb6f37c I have padding set to 4 for toolbar icon size 24x24 and larger, and 6 for < 24x24.  This was needed to prevent clipping the icons (the button needs to be slightly larger than the icon).  I'm a little unsure how hardcoding these values will affect themes and icons, so any testing will be helpful.  You can also try adjusting the padding values [here](https://github.com/IgnorantGuru/spacefm/blob/fb6f37c0740f393bda60a8deacfb1e2bbe9da831/src/settings.c#L9658).  Different padding values are used for GTK2 vs GTK3 there.

GTK3 didn't respond at all, and I also set all margins to 0 (a GTK3-only feature which apparently does nothing), and I set the toolbar container to have zero border (GTK2 and GTK3).  The only thing which had an effect on GTK3 was setting the padding (size request) higher than zero, which added more.  The Adwaita theme is definitely more wasteful of space than other GTK3 themes I tried (wastes about 3mm vertical compared to thinnest theme I tried).

So it seems like most of the padding in GTK3 is coming from the theme, which SpaceFM doesn't traditionally override.  But I'd consider it in this case if someone wants to come up with some GTK3 code for adjusting the style of a button (a GtkButton, not a GtkToolButton - see the code) or toolbar to remove padding (basically how to override the theme for this).  I don't usually get into theme hacking because it's very time consuming and tedious, and hacking styles in applications is generally poor form and troublesome.

Otherwise, I suggest a thinner theme, or hack Awaita to adjust padding values.  You might save 3-5mm vertically.

**Comment by IgnorantGuru** [comment]
Note, I have reverted the size requests (manual padding) on buttons because it was causing clipping of icons in GTK2, eg with no theme or other themes.  It's not good to hard-code such things because they are theme-dependent, so I think leaving it as-is is the best approach.  The code is still in there, I just commented it out for now.  And I left the GTK3 margin settings and toolbar border setting intact, in case they do some good.

If you would like to test the build that had the size requests and padding I mentioned above, you can download that branch like this:

     wget -O spacefm.tar.gz https://github.com/IgnorantGuru/spacefm/tarball/fb6f37c0

Then do the normal configure and make.

**Comment by HerborenInVlammen** [comment]
Thanks again.  In the future, if I want to implement the settings into
my personal gtk3 builds which lines would I uncomment?

**Comment by IgnorantGuru** [comment]
Just to record some notes here:
I see some old discussion of GTK3 not allowing gtk_widget_set_size_request to make a widget smaller [here](https://mail.gnome.org/archives/gtk-devel-list/2012-September/msg00062.html).  I didn't research that thoroughly, but if you or someone else wants to research it and find out if there is a solution for forcing the widget smaller, that might provide a way to adjust this.  @BwackNinja may also have input on this when he returns.

Back then they stated:
> In GTK+3, widgets receive *at least* what they requested in the size requesting phase.

> User facing apis cannot undermine the minimal requirements for the geometry which a widget has requested.

On my blog I rant regularly about GTK3, and this is another example where they have deliberately limited functionality compared to GTK2.

If that cannot be worked around, then I would say the style/theme would be a solution.  I considered using an hbox instead of a GtkToobar, but that would require some recoding, all for the sake of GTK3.  And it would likely only remove the padding which is above and below the buttons, not what is within the buttons.  Yet in Adwaita, most of the padding is within the buttons (or around the image in the button?)

**Comment by HerborenInVlammen** [comment]
Just a note for others who want the GTK3 toolbar button padding issue
mediated:

I have successfully edited several adwaita based themes to deal with the
issue.  Steps:

1) Open a Spacefm root window and navigate to your "/usr/share/themes"
folder.
2) Backup your theme's "*gtk-widgets.css*" file (found under the
"gtk-3.0" folder).
3) Open the *gtk-widgets.css* file using your favourite text editor and
search for something resembling the following (note that this was
different on each theme, but was fairly easy to find for each.  I
initially just searched for the "padding" entry and found the correct
entry eventually):

*.toolbar .button.image-button*

4) The padding settings were directly below this in most cases.  So
change the padding a few increments at a time; save the
*gtk-widgets.css* file WITHOUT exiting it.
5) Now go change to a different theme.  After it completely loads,
change back to the theme you are working on and view the changes.  If no
changes appear, or undesired changes appear, you have edited the wrong
padding setting.  If so, CTRL-Z your above changes and save, and keep
searching.  You will find it eventually.
6) Once you have the padding set the way you like it, save the whole
theme somewhere by archiving the parent folder.

Done.

**Comment by IgnorantGuru** [comment]
I did figure out how to remove the padding from the toolbar and buttons in 84b38e9.  This works for me with Adwaita - actually the toolbar comes out shorter than it was in 1.0.1 before the toolbars were changed.

I did add 1 px of padding to the top and bottom of the toolbar, otherwise the toggle buttons merged with the tab bar.

Also, the horizontal padding was removed from the buttons, which means more of them fit in the toolbar.

If that solves this problem you can close this issue.  Thanks for the theme info as well.

**Comment by HerborenInVlammen** [comment]
Thanks for your help.  It is solved for me as far as I am concerned.

**Comment by IgnorantGuru** [comment]
Okay, I;m not sure if you tried the latest, but to clarify, I did remove the theme's padding in GTK3, so you shouldn't need your theme hack - sorry for the wasted effort (welcome to my world).

**Comment by HerborenInVlammen** [comment]
LOL! 

I just built it.  And, I do have one issue. (You are gonna blow a
gasket) but the toolbar is too thin now and ignores theme settings as
you say.

So, in *settings.c *for future builds , please let me know what lines I
should manually edit to add or remove vertical padding until I find
something I like.  And then, I promise you will never hear from me again
on this issue (unless I need your help). :)

**Comment by HerborenInVlammen** [comment]
Is this the line?:

set_gtk3_widget_padding( toolbar, 0, 1 )

**Comment by HerborenInVlammen** [comment]
It is indeed the line, so forget it and for sure close this :)  Your
patience and skill is appreciated.
