### ISSUE TITLE
Latest working daily build changes file type icons

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#535]
Latest working daily build (1.0.1+201505150731.981~ubuntu14.04.1... the last daily 1.0.1+201505160731.974~ubuntu14.04.1, won't build) changes file type icons.  For example, all doc, odt, pdf, and so on icons are the same and mostly incorrect, as are archive icons and so on.  

This is from the Mati75 unstable ppa.  I tried to report this to the ppa maintainer as well.

**Comment by IgnorantGuru** [comment]
Changes in #530 made SpaceFM more Freedesktop compliant wrt its choice of icons for MIME types.  You say "icons are the same and mostly incorrect", but what do you base this on?  You'll need to examine the MIME type handling on your system to see why the icons that are being used are chosen.  If you find somewhere that SpaceFM is out of spec, you need to report that specifically.  Your report is too vague and general.

**Comment by HerborenInVlammen** [comment]
Your are right that was a bit vague.

Before this build, tar had a different icon from rar, bz, and so on. 
Now all archive types have the same icon.  Deb files have the same icon
as archives (yes they are archives) but had a gdebi icon before.... and
so on.

All documents from epub to doc, to odt, pdf and soon all have the same
icon now.  Whereas they all had different icons before the build in
question.  This is regardless of icon set chosen. 

If you wish, I can restore an earlier build, and show you a screen shot
of the icons that have been used for years, by spacefm... and then also
show you a screenshot of the file type icons with the latest build.  You
will see that there is a problem.

**Comment by IgnorantGuru** [comment]
It sounds like the MIME type definition files on your system are configured this way.  You're still not presenting anything to indicate that SpaceFM is out of spec in determining the default icon.  Some systems are setup to show similar file types with a generic icon.  Although if pdf is the same as odf, it sounds like your MIME system is incorrectly or uniquely configured.  Spec is [here](http://standards.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html).

Previously, SpaceFM was guessing the icon before checking the MIME XML files.  Now it only guesses if the XML files can't tell it what icon to use.  So it sounds like your problem is in your MIME XML files.

**Comment by IgnorantGuru** [comment]
For example, assuming PDF files on your system identify with MIME type "application/pdf" (which is not necessarily true depending on MIME config), SpaceFM would look for these files in this order (assuming standard system dirs are in use):

    ~/.local/share/mime/packages/application-pdf.xml
    /usr/local/share/mime/packages/application-pdf.xml
    /usr/share/mime/packages/application-pdf.xml

The first time it finds a &lt;generic-icon name=.../&gt; tag (or in the first file, it can also be a &lt;icon name=.../&gt; tag), it will use that icon.

So to change the icon used for PDF, right-click on a PDF file, right-click on any associated application, select the application-pdf.xml file from the <a href="http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-mime">MIME Menu</a>, and edit the file (*~/.local/share/mime/packages/application-pdf.xml*) to use an icon:

    <icon name="x-office-document"/>

Then update the database (and you may need to restart SpaceFM):

    update-mime-database ~/.local/share/mime

**Comment by HerborenInVlammen** [comment]
I do not know enough to know whether my mime system is incorrectly
configured.  It is vanilla Ubuntu Trusty using Faenza icons.  All I know
is that icons are now shown much differently than before... and when
plain text files for example now have the same icon as .css scripts and
.xml file than there is, in my mind, a problem.  Or, maybe it is just
something i need to get used to because it is radically different than
what I have used in Linux for years.

I know that comparing to another file manager can mean nothing, but
Nautalis shows all the mentioned file types  (in this thread)
differently in that archives have the same icon design but are different
colours for the different archives and so on, and xml and plain text
file have different icons etc..

And yes, odf files have the same icon as pdf etc..  Anything registered
as a document type such as epub, mobi, pdf, odf, odt, docx and so on all
now have the same icon when they were all different.

**Comment by HerborenInVlammen** [comment]
Thank you for this. 

I do think I have discovered a problem, maybe "the problem:  None of the
folders you show below contain specific XML files for specific file
types. I.e., there is no file in any of the folders name
"application-pdf.xml" etc...

Also Note that there is no folder "/usr/local/share/mime" on either my
Ubuntu desktop or my Xubuntu laptop.  Also, my Xubuntu laptop has
exactly the same files as my Ubuntu desktop in the said folders minus
files for apps I do not have installed on the laptop but do have
installed on the desktop and vice versa.

There is nothing unique about either my Ubuntu or Xubuntu installs; I
installed both clean (not upgrades), and both are Trusty and both are up
to date.

Attached are screenshots of the contents of the folders you mentioned
that do exist on my Xubuntu laptop (since I am now using it). 

If spacefm is searching for specific xml files for specific file types,
and these files do not exist, then I would say that is why this is
occurring.

**Comment by IgnorantGuru** [comment]
There are aliases in some XML files for other types, which may be why it's still finding an icon.  Just because SpaceFM is behaving differently doesn't mean it's wrong.  But it does seem strange that it's using a generic icon over a specific.  Perhaps it should use an icon tag if present, then guess the icon, then use a generic icon if present in that order.  I'll check the specs.  We could also ignore the specs, but other file managers may not use MIME for this so they are no indication of correct behavior.

**Comment by IgnorantGuru** [comment]
Also, your screenshots did not come through, but the icon is probably defined in  /usr/share/mime/packages/freedesktop.org.xml, which defines many types.

**Comment by IgnorantGuru** [comment]
It looks like SpaceFM is using the generic-icons from the spec wrong, so Ill be updating this.

**Comment by HerborenInVlammen** [comment]
XML files for specific file types are found under various folders under
"/usr/share/mime"

For example, the XML file for PDFs is "/usr/share/mime/application/pdf.xml"

This is the same on both my Ubuntu and Xubuntu systems.

Tonight at work I will check our systems which use strictly Xubuntu. 
Most are Trusty, but I think there are a few stand alones that are not
network active or allowed Internet access that are still Precise.  If
they all have the same folder structure and file contents for said
folders as both my personal Ubuntu and Xubuntu systems, then I would say
I have presented valid info LOL :)

I am just trying to help where I can with a program I love.  I can
imagine being a developer and having to deal with all the wishes and
foibles of thousands of users must be trying.

Your work is appreciated.  For myself, I cannot stand using Nautalis, or
Thunar (expecially Thunar) as they are lightweight toys compared to
SpaceFM.  I wish I could code so I could help out in a more meaningful
way other than to point out what I think are bugs.

Keep up the good work!

**Comment by IgnorantGuru** [comment]
Thanks for the info.  Indeed I gave you the wrong dirs.  SpaceFM looks in these files (eg for the plain name or user icon for MIME type application/pdf):

    ~/.local/share/mime/application/pdf.xml
    /usr/local/share/mime/application/pdf.xml
    /usr/share/mime/application/pdf.xml

But those files are actually created from the files in .../mime/packages/.  So to change the icon for a type, you can create ~/.local/share/mime/packages/application-pdf.xml (I think the filename is arbitrary, doesn't matter), then run

    update-mime-database ~/.local/share/mime

And ~/.local/share/mime/application/pdf.xml will be created automatically.

At any rate, the latest change in next should restore the original icons.  What it now does is it looks in ~/.local/share/mime/application/pdf.xml to see if there is an icon tag, and if so uses that icon.  Otherwise it guesses the icon (which is part of the MIME spec).

However, it should be noted that SpaceFM is not fully spec-compliant in this area, in that it does not read ~/.local/share/mime/icons or /usr/share/mime/generic-icons, etc.  The spec is a bit convoluted to support, and would kill performance.  But SpaceFM has been working this way for years with no complaints, except for #530, which has now been addressed.

User input is fine but these Freedesktop specs are hell to support - they are not written with performance in mind.

**Comment by HerborenInVlammen** [comment]
Thanks!

Since Mati75's ppa has not been working the last few days, I assume I
can always get the "next" build here?:

|https://github.com/IgnorantGuru/spacefm/tarball/next

|

**Comment by HerborenInVlammen** [comment]
Hey ... I just built the next daily, and the icon issue is fixed
completely as far as I can tell.  Thank you!!!

**Comment by IgnorantGuru** [comment]
Thanks for the followup and for taking the time to report your issues.  I do prefer to know what's going on even if not all of them are things to be fixed in SpaceFM.  (Some people have all kinds of strange systems and system issues, and a file manager gets blamed for them all, so I have to question reports carefully.)

You can always build any branch of SpaceFM and install it on top of a debian package - just use --prefix=/usr.  Then you can always reinstall the debian package to revert it.  I do this all the time even though purists will gasp.
