### ISSUE TITLE
[request] tree view should keep focus when selecting an item

### ISSUE THREAD

**Issue by jmcamp** [IgnorantGuru/spacefm#541]
I'm using Spacefm v1.0.1 on Arch Linux.

When selecting a new folder in the tree view, focus automatically moves to the file list.  This happens both when clicking on a folder name with the mouse and when using the up/down arrow keys.

Ideally the focus should stay on the tree view and not automatically move the file list.

Thunar had a similar problem, but a fix was recently made:
http://git.xfce.org/xfce/thunar/commit/?id=3ad690a7fdc1751f01ee9c7be458ecf29ea0c711

**Comment by IgnorantGuru** [comment]
This should now be done in the next branch, due for 1.0.4 release.  Please see README for testing this branch.

This also makes the dir tree navigable via keyboard, and you have to press Enter to enter the selected dir.

**Comment by IgnorantGuru** [comment]
On second thought, I'm going to revert this and leave it so that the file list gets focus when a side pane is activated.  I think it's logical since you're entering that directory.  I prefer to click on the side pane and then navigate with keyboard.  And keyboard users are likely to want to do so.

However the dir tree can now be navigated with keyboard, and you must press Enter to enter the dir.

This will also make it consistent with the other side panes.

**Comment by Vladimir-csp** [comment]
Enter in side pane brings focus to file list, because something was selected to be open in file list. That sounds logical.
