### ISSUE TITLE
handlers' %a as bash variable

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#547]
Hi!
All other variables in handlers have bash variables variants except %a.
Please add bash variant for %a, e.g $auto_mpoint and check if it was changed (exported?) by the script. This way handlers could change auto mountpoint without caring about how to open/close/delete them.

**Comment by IgnorantGuru** [comment]
If %a is in the command, SpaceFM creates an automatic mount point dir.  If it isn't, no moint point is created.  It's just a convenience feature.  A handler can always create its own mount point instead.  Or if you want a bash equivalent, just set myvar="%a"

Using %a does help with auto-open after a mount, since it will look to see if a device was mounted with that mount point, and the mount point dir will be deleted when no longer used.  But changing a bash variable in the script would not help because SpaceFM has no way of reading such variables back from the script.  If you don't use %a, you'll probably want to open your mount point manually on successful mount in the handler (spacefm DIR).

Rather than changing a bash variable and trying to read it (technically difficult given how SpaceFM runs scripts), it would be more feasible to have a socket command that can be used to update the moint point in use for a task (so SpaceFM will attempt to automount it when the handler task completes).  While more practical (although it too has some tricky issues), it seems redundant when another socket command (spacefm DIR) can be used to simply open the mount point.  I don't see a real need for it.

**Comment by Vladimir-csp** [comment]
handler would need to take care of removing the dir on failed mount attempt then...
SpaceFM also does not remove "%a" in unmount action if mountpoint is not in .cache/spacefm.

Maybe add a way to change mount prefix?

**Comment by IgnorantGuru** [comment]
I think the simpler solution if you don't like .cache location for mount points is to simply create a link to it wherever you want. I don't see a gain from a custom path - it's just an arbitrary path in the user's home.  What's to be gained from changing it vs simply creating a convenience link to it?  (Nor do I really understand why you're fighting with the default mount locations in general - what is being accomplished?)

You're pointing out a few areas of inflexibility, at least in terms of automated functions.  But automated functions always have inflexible elements or structure.  If you change those, then you need to recreate the automation in a custom way.  The convenience functions such as %a will always have specific limitations.

Overall, given how you seem to want a highly customised system setup, I would suggest creating a script with some convenience functions of your own, which can be used by your handlers.  This would replace %a, could cleanup mount points on events, etc.  I think your use is going beyond what SpaceFM's convenience functions are designed to handle, but not beyond what SpaceFM can do.

**Comment by Vladimir-csp** [comment]
The main issue is described in #548, .cache/spacefm is hard to find from anywhere outside SpaceFM, Other apps do not know about it, GTK file dialog does not list mounts from there.

**Comment by IgnorantGuru** [comment]
Allowing the mount path to be changed won't make it any more findable ootb.  

How about creating a symlink for your user:

    ln -s ~/.cache/spacefm ~/Desktop/Mounts

Then it can be bookmarked in Places as well.

I see what you mean by ootb behavior and that path being a bit obscure, but it is shown literally in the path bar.  Not sure what else would be appropriate.  As you observed, this is more of a DE integration issue, and SpaceFM is DE-independent (it is not a Gnome app).

**Comment by Vladimir-csp** [comment]
Yeah, that works for users who are able to understand what 'path bar' is and remember that some of the mounts could be found in different place than sticking out of the monitor right in their faces.
Well, I will rely on heavy handler and udevil hacking for my flock then.

**Comment by Vladimir-csp** [comment]
...and this is not really about DE integration. GTK and QT file dialogs are used by GTK and QT apps in general, including DE-independent apps. Therefore placing mounts in hidden subdirs by default is counterproductive regardless of DE, IMHO.

**Comment by IgnorantGuru** [comment]
> Therefore placing mounts in hidden subdirs by default is counterproductive regardless of DE, IMHO.

I agree with that.  If you have a better suggestion for a default mount location I'll consider it, but this is where other FMs tend to mount fuse, afaik, and experienced users look for it there.  And if it's simply a convenience issue, I think a link does just as well as an option.

Also note that while SpaceFM doesn't get into this in a hard-coded way, it provides many ways for you to integrate with events, etc.  For example, some users use a script which places icons to mounted devices on the desktop, and removes them when they are unmounted.  This is fairly easy to do in SpaceFM.  Just because such things aren't hard-coded, doesn't mean you can't create extended or DE-specific event handlers and plugins.  You can certainly add bells and whistles beyond the basic functionality.

Closing this as %a behavior probably won't be changed based on this, but integration can be further discussed in #548.
