### ISSUE TITLE
Desktop file execution using keyboard

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#549]
That's one strange bug.
I have a conky autostart item:
```
[Desktop Entry]
Type=Application
Exec=sh -c 'conky & sleep 20 ; kill $! ; exec conky'
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_IN]=Conky
Name=Conky
Comment[en_IN]=
Comment=
OnlyShowIn=LXDE;LXQt;
```

It launches conky, then relaunches it 20 seconds later to work around the vertical size update bug in conky. 
Anyway, the problem is:
When I launch it from SpaceFM by pressing Open>Execute with mouse, it behaves as it should.
But if I do the same thing with keyboard (menu key, navigate to Open>Execute with arrow keys, Enter), first conky execution fails dropping this to stderr:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1a02538
  Serial number of failed request:  453
  Current serial number in output stream:  453
```
The rest of shell command works and after 20 seconds sleep second conky starts up.

**Comment by IgnorantGuru** [comment]
I can't explain why those methods would differ.  Activating a menu item via keyboard runs the same function.  The desktop window is being passed correctly in both cases, and the screen is found, and they are the same with both methods.  WINDOWID and DISPLAY in the environment are also the same.

You can try this in a desktop file to see the environment:

    Exec=env ; read
    Terminal=true

Also note that you can just select a desktop item and press Enter, you don't actually need to use Open|Execute.

Also, SpaceFM already runs Exec lines in bash, so you should be able to just use:

    Exec=conky & sleep 20 ; kill $! ; exec conky

However, SpaceFM will probably be the only application that will execute that in a shell - in others you'll need to run the shell like you did.

It may just be some trivial window focus difference when the command is run that is causing a problem in conky, or there is some difference in the environment.  This doesn't look like a problem with how SpaceFM is running the command, as it does exactly the same thing in both cases, and other applications work okay.  Also, with your Exec line it's actually the shell that is running conky, not SpaceFM directly.  You might try using bash rather than sh.

**Comment by Vladimir-csp** [comment]
Environment of first command in sh differs only in DESKTOP_STARTUP_ID, which is expected.

.desktop file is in .config/autostart, so it is not designed specifically for SpaceFM, but for session autostart. I've just found this situation launching it from there.

I also have doubleclick execution disabled in SpaceFM, that is why I'm using menus.

**Comment by Vladimir-csp** [comment]
Also, if I use other application to test instead of conky, i.e. leafpad, it works.

**Comment by IgnorantGuru** [comment]
> I also have doubleclick execution disabled in SpaceFM, that is why I'm using menus.

The 'Click runs executable' setting should not affect the desktop applications.

**Comment by IgnorantGuru** [comment]
You might also try a "sleep 0.1;" before your first conky command, in case there is some race involved with X resources, perhaps faster with the key since the menu isn't being shown and destroyed.

And I notice you use 'exec conky' for the second run.

In case you want to test any differences, apps are spawned from [vfs_exec_on_screen](https://github.com/IgnorantGuru/spacefm/blob/e568970e22b8f67af6615e525c44375d5324295e/src/vfs/vfs-execute.c#L105).

**Comment by Vladimir-csp** [comment]
Sleep helped, some race condition indeed.
I use exec to get rid of redundant sh process.

**Comment by IgnorantGuru** [comment]
I don't think it's any problem in SpaceFM.  As you can see, all it does is set a few env vars (which it seems to do correctly) and spawn an async process.  There's also some startup-notification code in there.

Perhaps conky is trying to do something with the desktop at the same time SpaceFM is showing the menu off the desktop or doing the startup-notification with the desktop as the parent.  Seems odd though.

Closing but feel free to add more info.
