### ISSUE TITLE
Missing and wrong icons for scripts

### ISSUE THREAD

**Issue by R-a-l-f** [IgnorantGuru/spacefm#554]
Hi,

for scripts and links to scripts no icons are shown by spacefm-gtk2 1.0.2. The only exception were icons are shown, are scripts that use #!/usr/bin/env, they get the icon for binaries.

Edit: Five hours later I noticed that tar.gz archives are also missing icons.

Regards,
Ralf

**Comment by IgnorantGuru** [comment]
The associated icon is taken from the MIME database on your system.  In some cases it will fall back to a generic icon.

If you right-click on a script, then enter the Open submenu and right-click on an associated application, you can use the [MIME Menu](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-mime) to explore the associated database files.  For example, to set a custom icon for scripts, select the application-x-shellscript.xml file in the MIME Menu and add an icon as shown in the comment.

I can't explain why just those files wouldn't show an icon on your system, but it's likely due to MIME configuration, not SpaceFM specifically.  However, some of the MIME handling did change in 1.0.2.
