### ISSUE TITLE
Remove noatime for USB, but access dates not changing

### ISSUE THREAD

**Issue by Geyup** [IgnorantGuru/spacefm#557]
I have a usb drive with two partitions, ext4 and ntfs and this is the output from the terminal when I mount the usb drive.

udev added:   /dev/sdb
udev added:   /dev/sdb1
udev added:   /dev/sdb2

Selected Device Handler 'Default': MOUNT [*]

TASK_COMMAND(0x149f000)=/usr/bin/udevil mount /dev/sdb1 -o 'noexec,nosuid'
SPAWN=/bin/bash  /tmp/spacefm-foo-2c527c50.tmp/07681d64-tmp.sh  run
    pid = 2169
mount changed: /dev/sdb1
child finished  pid=2169 exit_status=0

As you can see I removed 'noatime', but when I access my files, folders, etc., in the usb, the 'access' dates are not changing. I never noticed till now that spacefm started by default usb with noatime and now I have access dates for many things saying 1969, LOL...

Removing noatime should allow the access to change again, but it's not and I've even rebooted my system and restarted spacefm several times with no change. :(

**Comment by Geyup** [comment]
Ok after hours of playing I figure this out. 

I'm using udevil with SpaceFM 1.0.2, and I always assumed, when you right click on a USB device you can change the mount options in SpaceFM and remove the noatime and make this work, but it doesn't.

I had to go and remove the noatime from udevil.conf and now it works.

So I'm a bit confused, why have a GUI option in SpaceFM that doesn't work, or it should? If it should work it doesn't for a USB device, you have to remove noatime for the filesystem you are using in udevil.conf.

**Comment by IgnorantGuru** [comment]
> So I'm a bit confused, why have a GUI option in SpaceFM that doesn't work, or it should?

It does work, in that within SpaceFM you're defining what (user) options SpaceFM passes to the mount program.  Yet as it reminds in that dialog: "Note: Some options, such as nosuid, may be added by the mount program even if you don't include them."

There is some overlap there because some mount programs, such as udisks, don't add noatime, don't conveniently allow users to add other options by default, or don't allow for filesystem-specific options.  SpaceFM works with any mount program, not just udevil.  Even with udevil, there is a difference between options enforced by root (via udevil.conf) and options added by a user on a per-use basis.

As for noatime specifically, at least some installations of udisks didn't add noatime, yet this is almost always desirable for performance.  So SpaceFM passes it by default.  udevil also adds it as a default, because udevil is also used by devmon and via the command line, where it's also usually desirable.  So merely adding it in one place wouldn't cover everything.

So mainly you're encountering a bit of redundancy due to SpaceFM's ability to use multiple mount solutions.  If it only used udevil, noatime would probably only be in one place.

It's unfortunate it took hours for this to become clear - I've made a note to make it more clear in the next user's manual - but getting to know the role of udevil.conf is valuable because it gives you a lot of convenient control.

**Comment by IgnorantGuru** [comment]
Also note that you can run udevil with the --verbose option, which will show the exact 'mount' command udevil is executing, including options passed.  And as you saw, SpaceFM shows the exact udevil command it executes, including options passed.  So between the two you can see exactly what is being run, which is useful for troubleshooting.  Any command SpaceFM executes, you can also run yourself in a terminal for direct testing (taking SpaceFM out of the troubleshooting loop).

**Comment by Geyup** [comment]
To start with, I don't have udisk installed, only udevil.

So you're saying, as a user, if I right click on a USB devivce and go to;

```Settings > Mount Options > and change this to; noexec, nosuid``` This should work for that device? Because if that is true it's not working. As a user it only worked for my usb devices using ext4 and ntfs when I removed noatime from udevil.conf.

So again, this is where I'm confused, seeing the ```noatime``` optiion for the Mount Options, removing it, and not having it work, and needing to edit a config file. It just seems like this should be working through the GUI, since the option is there, to lead the user into thinking, that's what it's there for.

I just think, that if an end-user is only installing SpaceFM and udevil, the end-user shouldn't have to edit config files if an application has options to make changes via the gui, I hope this makes sense, it does to me, otherwise, why have the option. So maybe in the future you can write SpaceFM, so when any of the mount options are changed, then they are reflected in udevil. Because if not, then I really don't understand having udevil, I thought whatever was changed in SpaceFM is changed in udevil, or vice versa...
