### ISSUE TITLE
Lastest "next" versions (db68eb0) uses the wrong config for the root account.

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#561]
The last two "next" builds of spacefm use the "/home/user/.config/spacefm" config for the root instance of spacefm instead of the "/root/.config/spacefm" config.  These should be seperate.

**Comment by IgnorantGuru** [comment]
I doubt there were recent changes which affected this.  It may be caused by your environment variables.  How are you running the root instance?

If running it directly, you'll generally want to explicitly set HOME=/root

If starting it via File|Root Window within SpaceFM, HOME=/root is set automatically.

**Comment by HerborenInVlammen** [comment]
I restored to last week's Clonezilla image and then rebuilt Spacefm  w/
the latest "next" and it is fine now.  I have no idea what happened
during the build before that would have caused this.  But even a
complete uninstall including configs did not fix it. 

As usual I am a bit quick to post an issue.  Sorry about that.
