### ISSUE TITLE
~/.gtk-bookmarks is deprecated

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#573]
I do not know the details, but it seems that file dialogs initiated in any gtk applications, both gtk2 and gtk3 do not use `~/.gtk-bookmarks` any more, but use `~/.config/gtk-3.0/bookmarks` instead. (as of debian testing and possibly even stable). Please change source of gtk bookmark import accordingly.

**Comment by Vladimir-csp** [comment]
I've tried this:
```
-        file = g_build_filename( g_get_home_dir(), ".gtk-bookmarks", NULL );
+        file = g_build_filename( g_get_user_config_dir(), "gtk-3.0/bookmarks", NULL );
```
It works, but it may require changes in parser to extract bookmark names from URLs, since bookmarks file has only one column now.

**Comment by IgnorantGuru** [comment]
Thanks, this has been corrected in next, due for 1.0.4 release.

The files seem to have the same format - if you rename a GTK3 bookmark then the line will have two columns like in GTK2.  However I changed the import function (for both) to use the basename as the name if no name is present, rather than showing the full path.

If using GTK3, it will look for the new bookmarks file to import, otherwise will fall back to GTK2's bookmarks file.  If using GTK2, it will only look for ~/.gtk-bookmarks.

**Comment by Vladimir-csp** [comment]
Thanks!
As I said, both gtk2 and gtk3 apps initiate a file dialog that works with new file, so IMHO, both versions should prefer new file and fall back to old.

**Comment by IgnorantGuru** [comment]
Okay, I've made both use the GTK3 location, falling back to the old.  If you know exactly what version of GTK2 began using the new location, we could force it to use the old location for those versions if present, so it will be consistent with the file chooser dialog.

**Comment by Vladimir-csp** [comment]
I do not know the exact version of gtk itself, but this [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760311) for mate component is year and a day old, and it states that xdg-user-dirs-gtk version 0.10 changed behavior. I think, it is pretty safe to make this change.
