### ISSUE TITLE
separate translation strings

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#580]
Please separate translation strings: "_New" in file list context menu and "_New" in Event manager|Tab|New.

**Comment by Vladimir-csp** [comment]
labels in Event manager in general should be separate strings, different wording specifics there.

**Comment by IgnorantGuru** [comment]
Thanks, I added some contexts, but not for all of them because I don't want to break existing translations too much.  I think those should cover it.

Note that spacefm.pot is currently being pushed to Transifex from the alpha branch since Sep 13, not the next branch.  alpha is ahead of next and includes this change. But you can use either branch to test this.
