### ISSUE TITLE
spacefm reads constantly from files?

### ISSUE THREAD

**Issue by nioncode** [IgnorantGuru/spacefm#598]
Some background information:
I have a USB flash drive reader with some additional behavior from the flash controller. If I write a 512 Byte block with special syntax to a file, instead of writing the data to the file, the flash controller generates a response.
When I then read the same block from the same file again, instead of giving me the actual content of the file, the flash controller will return the previously generated answer. This happens just once though, every time I read the block in the future will return the content of the file just like a regular flash controller.

The issue:
When I have the folder with the special file open in spacefm and send a request to the flash controller, most of the time I will not receive the answer back. Instead, I will get the content of the file. This indicates, that spacefm 'steals' the answer before I have a chance to read it.
This makes the device (which is usually used by background applications) unusable for me whenever I do some work in spacefm on the flash drive.

What could be the cause of this?
Currently I work around this by creating the special file in a deep folder hierarchy to make sure I don't use it during day to day use. But this is not a real fix.

**Comment by IgnorantGuru** [comment]
When you a have a dir open in SpaceFM, and a file in it changes (per an inotify kernel watch on the dir), SpaceFM will reload properties of the file, including it's MIME type.  This may involve opening the file and reading a portion of it (per MIME specs).  However, files in subdirs will not be read.

That's the only thing I can think of that would affect this.  You might avoid it by adjusting your MIME setup so files of that type are identified by name only.  See MIME Menu in SpaceFM's manual for a few options in adjusting how files are identified.

**Comment by nioncode** [comment]
Yes, MIME type detection seems a reasonable candidate.
Is there a specification about how many bytes from the file are read to determine the MIME type?
I just did a bit trial and error and found something between 19-20 kb to be the magic boundary where things stop working. So, when I write to a position bigger than 20kb in the file, everything works fine.

**Comment by IgnorantGuru** [comment]
I've seen it done like this as part of the Freedesktop spec:

~~~~
<magic priority="50">
    <match type="string" value="\x89PNG" offset="0"/>
</magic>
~~~~

Usually just the first few bytes are read.  I think if the file has a specific name and you use that as a glob in the xml; that might prevent it being opened, since it can be identified by name.  I didn't write that part of the code so I can't guarantee it, but it makes sense to do it that way.  Or, if the spec insists on reading contents then it might not.

**Comment by nioncode** [comment]
I'd rather fix this in my application accessing the hardware (by using higher offsets in the file instead of the first few bytes) instead of fixing it locally on my machine, because I use the application on multiple machines.
I'm a bit baffled that I need to go as high as 20kb to make it work reliable, though. I imagined the MIME type recognition only checks the first few hundred bytes. However, it does not really matter if the file is 1kb or 100kb in size, so I might just choose to be on the safe side and choose some bigger value.

**Comment by IgnorantGuru** [comment]
It could be because you can't really just read the first few bytes of a file, they're read in blocks.  Usually 4k blocks are the minimum but the way it's implemented the OS or filesystem may read a larger chunk, even if SpaceFM only reads several bytes.  Or you could look through the MIME xml files and see if there's a magic offset that's that high, but I would doubt it too.
