### ISSUE TITLE
could not unmount the CD-drive without udevil.

### ISSUE THREAD

**Issue by vasisualiy** [IgnorantGuru/spacefm#606]
I use spacefm with a udisks2 backend. All goes ok, but only one thing: optical drives.

spacefm automounts optical drive without a problem, but if I want to eject/unmount it, spacefm throws me an error:

/tmp/spacefm-dikiy-0b406d27.tmp/63a5f974-tmp.sh: line 126: udevil: команда не найдена

**Comment by IgnorantGuru** [comment]
It looks like the default order of the handlers is a problem.  If you open Devices|Settings|Device Handlers, and move the "udevil iso unmount" handler down to the bottom of the list, or disable it, that may solve the problem.  It looks like that handler is being used for iso9660 in preference to the Default handler.

**Comment by vasisualiy** [comment]
ok. It works. But why the problem is triggered only on unmount, but not on a mount too?

**Comment by IgnorantGuru** [comment]
ISO files are mounted via a file handler rather than a device handler.  But they are unmounted via a device handler.  So only an unmount device handler command exists for iso9660.  I just need to adjust it so it only applies to iso files rather than any iso9660 fs.

**Comment by vasisualiy** [comment]
>ISO files are mounted via a file handler rather than a device handler. 
but optical drive is mounted over a device handler too, isn't it?

**Comment by IgnorantGuru** [comment]
> but optical drive is mounted over a device handler too, isn't it?

Yes, but there is nothing to interfere with it, as there is in the unmount case, where the unmount handler for ISO files is being erroneously used for a mounted CD.

If you run the first instance of spacefm in a terminal, you can watch the output while it's running, and it will show which handler it is using to mount and unmount things, as explained at the end of [this section](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#handlers-dev-white).

**Comment by IgnorantGuru** [comment]
This should now be fixed in the next branch, due for 1.0.5 release.  When you upgrade to next or 1.0.5, the Whitelist and Blacklist for the 'udevil iso unmount' device handler should be automatically changed to:

Whitelist: +iso9660 +dev=/dev/loop*
Blacklist: optical=1 removable=1

Also, there was a bug in 1.0.4 and prior which caused the whitelist to be tested incorrectly in some conditions.  This has been corrected.  So simply changing the whitelist and blacklist may not work correctly - you'll need to also upgrade to next or 1.0.5 (when released).

For testing the next branch see the Net Installer on the homepage.

@vasisualiy For testing this fix you should move the handler back to its original position in the list - before the Default handler.
