### ISSUE TITLE
Question about GTK+ widgets

### ISSUE THREAD

**Issue by hasufell** [IgnorantGuru/spacefm#616]
I am currently writing a [filemanager](https://github.com/hasufell/hsfm) and am wondering what widgets you used for the **Compact Style view**.

The "Detailed" style view is obviously done via `GtkTreeView`, the "Icons" style view via `GtkIconView`, but both don't seem much like the "Compact" view.

The codebase is so huge I don't even know where to look for.

**Comment by IgnorantGuru** [comment]
Hi hasufell, Nice to hear you're working on a FM.

SpaceFM's file list views actually use custom widgets that are part of the exo library.  The Icon and Compact views both use the ExoIconView widget, and the Detailed view uses ExoTreeView.  These are analogous to and based on GtkIconView and GtkTreeView, but use custom methods for additional features.  In some cases we use GtkIconView and GtkTreeView functions directly on ExoIconView and ExoTreeView widgets, respectively, as they are somewhat interchangeable, while in other cases exo functions are used instead.  So you'll see a mixture of both.

Exo is part of XFCE and Thunar development.  SpaceFM, originally based on PCManFM, uses a reduced fork of the exo library which is included in SpaceFM's src/exo dir.  Our fork of exo, while now somewhat dated, includes some bugfixes, custom changes, and also supports GTK3 (XFCE's exo currently only supports GTK2 afaik).  Yet we don't follow upstream.  I would suggest asking @OmegaPhil any questions re exo use or links, what version or branch to use, etc., as he recently did some work with their code and ours.  I've mostly just bugfixed a few things in our exo fork.

To see where SpaceFM creates the file list widgets, see the [create_folder_view()](https://github.com/IgnorantGuru/spacefm/blob/24f118d60c5370489b94795ed0a58aa4c799d5aa/src/ptk/ptk-file-browser.c#L4147) function in ptk-file-browser.c.  You'll see exo_icon_view_new() and exo_tree_view_new() called from there, and you can track those functions down in the exo code as a start.

Feel free to ask where things are because I know SpaceFM's code well.  Also note that SpaceFM's code can be challenging to follow, as it was built as a custom prototype on top of PCManFM.  It's only about 15% original PCManFM code at this point.

BTW what VFS (eg gvfs) and/or device daemon (eg udisks, gudev, udev) is your FM based on?  Last I spoke to PCMan, he was working on a fuse-based API to eliminate udisks - you might want to check how that is progressing before investing in udisks, which is very high maintenance and buggy.  Choose carefully early in the project.  I have found that udevil works well as a replacement for udisks - much less trouble.  Ideally, I recommend allowing some configurability in this area.

**Comment by IgnorantGuru** [comment]
Also, if you want to support both GTK2 and GTK3, see SpaceFM's gtk2-compat.h for ideas (as well as a few conditional build areas in the code).  Not so difficult to do, and this gives you insurance against radical changes in GTK3 (you can abandon it if it becomes too bad), and gives your users a choice.

**Comment by hasufell** [comment]
> BTW what VFS (eg gvfs) and/or device daemon (eg udisks, gudev, udev) is your FM based on?

Currently none (using low-level POSIX functions). There are haskell bindings to the gnomevfs library, so I'll probably switch to that at some point. Everything is pretty much in flux right now.

> Our fork of exo, while now somewhat dated, includes some bugfixes, custom changes, and also supports GTK3 (XFCE's exo currently only supports GTK2 afaik).

That sounds like you should make it a real library, so people can pick it up, create language bindings and so on.

But it's good to know that the stuff is based on `GtkIconView`. Maybe it's not too hard to come up with something after all.
