### ISSUE TITLE
It's defficult to click a last file in "View -> Style -> detailed" mode.

### ISSUE THREAD

**Issue by queenmedley** [IgnorantGuru/spacefm#632]
When I set  detailed mode, horizontal scrollbar appeared and cover last file at bottom in window.
So it 's really hard to click the last file.
I think it need some margin at bottom in detailed mode.

**Comment by IgnorantGuru** [comment]
This type of behavior is almost always due to use of a 3rd party GTK theme which is broken or incompatible with your current version of GTK.  You should report this to the theme developer.  Or to reopen this issue here, you will need provide reproducible steps using GTK's default theme (Adwaita for GTK3, or Raleigh for GTK2).

Normally, the horizontal scrollbar only appears with oversized columns, and does not cover a clickable file.  The scrollbar disappears when not needed (when the cumulative column widths are less than the file list's width).

**Comment by IgnorantGuru** [comment]
Could be related to #612
