### ISSUE TITLE
Speedup loading thumbnail from its cache

### ISSUE THREAD

**Issue by Hadden89** [IgnorantGuru/spacefm#639]
I recompiled this cool file manager from sources, master branch. (I hadn't the video thumbs from the .rpm).
How the cache file works? All video/image seems to works well.
How to make them persistent in a cache file, so when I reopen that file(s) are still there?
In the specific case, I'd like to make cache of some smb cifs folders (thumbs doesn't hang spacefm too much, which is great)

*edit*
My fault. Actually the thumbs are cached in .thumbnail hidden folder under my home.
But when I open cached folder it still a bit slow to open the previews, probably also the machine is not very recent (is an "old x86" dual core).
It's possible to speed up the process? Maybe increasing spacefm process priority?

**Comment by IgnorantGuru** [comment]
As you found, thumbnails are cached in ~/.thumbnails/normal/  When you first enter a dir, thumbnails for each video or image file will be created and stored there.  The next time you enter that dir, most thumbnails will be loaded from the cache.  If a file has been modified, its thumbnail will be updated in the cache.

SpaceFM backgrounds the thumbnail loading in a low-priority thread so that it doesn't slow down the GUI responsiveness.  To change the priority of that thread you'd probably need to change the SpaceFM source code.

On a slower system, you might try a smaller thumbnail size, since large thumbnails take large amounts of memory (which can slow down the system, causing it to swap, etc), and also load more slowly due to their size.

**Comment by IgnorantGuru** [comment]
Also, when changing to a smaller thumbnail size (in Preferences), then manually delete the ~/.thumbnails/normal directory.  Otherwise SpaceFM will continue to use the already-cached larger thumbnails.
