### ISSUE TITLE
custom icons for bookmarks

### ISSUE THREAD

**Issue by kalamalka** [IgnorantGuru/spacefm#641]
It think it would be  nice feature to have custom bookmark icons, where the user could choose from system icons, or custom ones. 

thanks for your awesome work!

**Comment by IgnorantGuru** [comment]
SpaceFM (>=1.0.1) does support custom bookmark icons.  You can set a default bookmark icon by right-clicking on Bookmarks and selecting Settings|Bookmark Icon (click the Choose button to choose an icon visually).  Or you can right-click on a bookmark and select Properties to set a custom icon per bookmark.  [more info](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#gui-book)

**Comment by kalamalka** [comment]
oh it seems I am running 0.9.4. If I update will all my bookmarks and settings be lost? how do I update?

**Comment by IgnorantGuru** [comment]
If you installed SpaceFM from a distro package, you should notify the package maintainer that their package is out of date (usually file a bug on the package with your distro).  Then they'll update it.  And/or you can build SpaceFM using its [net installer](http://ignorantguru.github.io/spacefm/#installer).

Upgrading should retain all bookmarks and settings - see [1.0.1 release notes](http://ignorantguru.github.io/spacefm/news.html#1.0.1).  If you are concerned about the upgrade you can make a backup of your configuration directory first:

    cp -a ~/.config/spacefm ~/.config/spacefm-backup-0.9.4

**Comment by kalamalka** [comment]
Thank you for this information. I was successfully able to install the new version, however my bookmarks seem to be missing. I did that come up and I have looked into the directory /.config/spacefm   and see that my bookmark file is still there from what seems to be the last installation. 

 is there a different directory that I need to copy and paste the bookmarks file to?

**Comment by IgnorantGuru** [comment]
> I have noticed that all of the file menu options are missing and only show a drop tab that says 'activate' on all the file, view, devices etc..

This could be a malfunction in a 3rd-party GTK theme (eg make sure there are no warnings displayed when running spacefm from a terminal - you may need to update your theme for your current version of GTK).  Such behavior can also be caused by panel apps that attempt to steal GTK menus and display them elsewhere (eg #49 #518).  If so you may need to forgo such an application or report a bug against it.  You could also compare GTK2 and GTK3 builds of SpaceFM.

This isn't likely a problem in SpaceFM itself, but in the system its running on (GTK build, theme, panel, etc).  It's also remotely possible that something went wrong during upgrading, but people upgrade from 0.9.4 all the time without issues, and merely upgrading isn't likely to cause such a thing.  But if you want to open a report on this please use a new issue, include the output of 'spacefm --version', your current GTK lib version, your distro, and any GTK theme you're using.  At most we can probably collect information on the problem to help determine what on your system is triggering that.  It's good to test with a fresh config to see if the problem exists, and to determine any steps required to reproduce it. To test with a fresh temporary config:

~~~~
killall spacefm
spacefm -c /tmp/spacefm-test
~~~~

> Also none of the keyboard shortcuts seem to work either, for example CTRL D does not create bookmark.

I can't explain how none of the shortcuts would work, and no other reports of that, although there have been some changes re international keyboards since 0.9.4.  You can try setting the key shortcut again to see if that corrects it.  If it persists please open a new issue with all details and steps to reproduce (starting from a fresh config).

Thanks for your donation!

**Comment by kalamalka** [comment]
thanks for your reply. I have filed a new report [HERE](https://github.com/IgnorantGuru/spacefm/issues/643)
