### ISSUE TITLE
When using the Copy Path action, an extra blank space is added to the beginning of the path

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#664]
When using the "Copy Path" action, an extra blank space is added to the beginning of the path but outside of the quotes.  For example:

/usr/share/themes

is copied as:

_'/usr/share/themes'
with the above underscore signifying a blank space.

Not serious, but if used a lot gets annoying as heck.

**Comment by IgnorantGuru** [comment]
This is deliberate so that you can paste them into a terminal, one after another, without adding spaces.  If you select more than one file and do Copy Path, you'll see a space between each as well.

If you don't like the way that works, note that you can write your own Copy Path command using [sockets commands](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#sockets) to parse the selected files, and to place them on the clipboard however you like.  Just see some of the socket command examples in the manual to get started.
