### ISSUE TITLE
sub-class mime types

### ISSUE THREAD

**Issue by rmlrml** [IgnorantGuru/spacefm#683]
I have some opus audio files, which spacefm identifies as 
Type "Ogg Audio", MIME Type "audio/ogg"
but thunar identifies as 
Type "Opus Audio", MIME Type "audio/x-opus+ogg".

Some results from grepping through /usr/share/mime:

`/usr/share/mime/audio/x-opus+ogg.xml:  <sub-class-of type="audio/ogg"/>`
`/usr/share/mime/globs:audio/ogg:*.opus`
`/usr/share/mime/globs:audio/x-opus+ogg:*.opus`

So I guess that means my files' .opus extensions could signal either the opus codec audio file format, which they are, or they could just as well signal a generic ogg container file, agnostic of the audio codec inside ... That annoys me, but at least it seems to tell me that technically both spacefm and thunar are correct.  It's just that MIME is allowing for more than one "correct".  Maybe I misunderstand.

Assuming both file managers are using MIME to determine file type, what might they be doing differently?  I didn't intend this post as a gripe, bug, or feature request, just a question.

**Comment by IgnorantGuru** [comment]
File identification is done differently by FMs using varying libraries and code, which obey MIME (which is a specification) to varying extents, partly because the specification is itself dysfunctional.

I recommend having a read through SpaceFM's [MIME Menu](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-mime) section of the manual, which explains how SpaceFM specifically handles MIME, and gives instructions for changing the behavior for specific file types, at least within SpaceFM, and generally system-wide.
