### ISSUE TITLE
[solved] GtkPlacesSidebar overpopulated with cgroup mounts

### ISSUE THREAD

**Issue by biopsin** [IgnorantGuru/spacefm#691]
Hi,
I noticed while I sandfox a application, I get a list of extra mountpoints or what to call it.
Please look at attachments.. this example happens while copy/move file to location..
:no sandfox running
![nosandfox_scrot](https://user-images.githubusercontent.com/7681285/28960786-39523bd6-7900-11e7-9db3-43516aa1203e.png)
:sandfoxed browser
![sandfoxedbrowser_scrot](https://user-images.githubusercontent.com/7681285/28960787-397cb62c-7900-11e7-92b6-d1acd83e3980.png)
Is there a way I can hide them? (rightclick delete is greyed out)

**Comment by IgnorantGuru** [comment]
That's unusual, perhaps an aspect of GTK that's newer than the version I'm using.  I can tell you that the Places sidebar is populated automatically by GTK (as a GtkPlacesSidebar), so if it can be configured, it would be through GTK's settings file(s).  eg maybe an option to not show some kinds of mounts.  That's why these are being shown: they are bind mounts.  But in my experience, Places doesn't list bind mounts.

**Comment by Vladimir-csp** [comment]
These are cgroup mounts.
I'm using Debian testing and I observed this behavior for some time in both gtk2 and gtk3 file chooser dialogs. It appeared with some upgrades, and then disappeared with later upgrades.

**Comment by biopsin** [comment]
Thank you both for the explanations, now I know where to look.
