### ISSUE TITLE
Mount as root changes...

### ISSUE THREAD

**Issue by VastOne** [IgnorantGuru/spacefm#701]
When you mount as root in the past the normal user could always access the mount...

Now only root can access it. And in order to do so you have to open SpaceFM as root.. so it really makes no sense to even have a mount as root if you have to open a root SpaceFM to access it

If this is normal and to be expected, fine I'll accept... Just stating that it is a change

**Comment by IgnorantGuru** [comment]
Hello VastOne.  As you probably know, you can click Edit in that dialog to change the command used.  By default it runs udisks for this, because udevil disables the root user by default, but udevil can also be used.

If the default behavior has changed, this probably means udisks' default behavior has changed, or it has been changed on your system.

Probably should leave it up to the admin to configure default root mount behavior in udisks or udevil, or alter the command SpaceFM uses?  Perhaps an option can be added to SpaceFM's default command to change udisks behavior.  (I don't currently even have udisks installed so suggestions welcome.)

**Comment by VastOne** [comment]
Agreed IG it should be up to the admin only.. will close this as a non issue
