### ISSUE TITLE
Can't perform another action when transferring files...

### ISSUE THREAD

**Issue by sla0101** [IgnorantGuru/spacefm#703]
This has been happening with 1.0.4 and 1.0.5.

If I transfer a large file over usb, I noticed there are a lot of functions I can't peform until SpaceFM has completed the transfer.

Here are some things I've noticed I can't do.

1. Can't rename or delete files or directories
2. Can't unmount/eject another usb device plugged in a usb port
3. Can't copy anything to another usb device plugged in

One thing that is really important for me to accomplish is the ability to transfer data to two seperate usb devices plugged in at the same time, but this doesn't work. If I try this, in the Task Manager I just see it sitting waiting in a queue.

I thought since these are different devices, plugged into different ports, I could transfer data back and forth at the same time, but this is not possible.

**Comment by IgnorantGuru** [comment]
If SpaceFM becomes unresponsive copying files, it's almost always due to delays in the underlying filesystem or system, and usb is particularly prone to this.  Also, different file managers respond differently to underlying system delays.

For details on how the Smart Queue works, how to disable it, and how to resume tasks manually, please see the [manual](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#tasks-menu-smart).  I see no problem copying directly between two usb devices, and there are no reports of any malfunction in the queue behavior.

It you believe there is a specific bug, you will need to provide exact steps to reproduce, one topic per issue please.
