### ISSUE TITLE
Not possible to paste

### ISSUE THREAD

**Issue by lpvm** [IgnorantGuru/spacefm#705]
When I `copy` or `cut` a file, the `paste` option is **always** dimmed.
I can drag and drop from one pane to the other, though.

Why is the `paste` option dimmed?  How to enable it?

**Comment by IgnorantGuru** [comment]
I haven't seen any other reports like this.  If you don't have write access to the current directory, then Paste will be disabled.  Move to a directory where you have write access, such as your home directory.

If that's not the problem, check the context of that menu item:
In the right-click menu of the file list, please RIGHT-click on the Copy menu item and select Properties from the Design Menu.  On the Context tab, check option 'Ignore Context / Show All' and click Ok.

Next, in the right-click menu of the file list, RIGHT-click on Paste if possible, and select Properties from the design menu.  On the Context tab, make sure there are no rules listed in the rules box.  If there are any rules, remove them.  Then also UNcheck option 'Ignore Context / Show All' and click Ok.

That should correct the problem if it was due to a custom context setting causing that menu item to be disabled.

If that doesn't fix it, please provide the output of 'spacefm --version' and your full GTK version.  Specify how you're copying the file (eg key shortcut or selecting Copy from menu), and any other details that may be relevant.

Starting the first instance of spacefm in a terminal may also provide some useful output, such as warnings.

**Comment by lpvm** [comment]
I have write permissions to the directories I'm trying to paste into.
Regarding the right click in the copy menu, it's done.
The right click on the Paste menu is not possible.

I'm using Void LInux with the following packages:
```
spacefm-1.0.5_1
gtk+-2.24.32_1                               The GTK+ toolkit (v2)
gtk+-devel-2.24.32_1                         The GTK+ toolkit (v2) - development files
gtk+3-3.22.26_1                              The GTK+ toolkit (v3)
gtk+3-devel-3.22.26_1                        The GTK+ toolkit (v3) - development files
gtk-doc-1.26_2                               Documentation tool for public library API
gtk-engine-murrine-0.98.2_5                  GTK2 engine to make your desktop look like a murrina
gtk-update-icon-cache-2.24.32_1              The GTK+ toolkit (v2) - The GTK+ update icon cache to
gtk-vnc-0.6.0_2                              VNC viewer widget for GTK
gtk-xfce-engine-3.2.0_2                      Xfce GTK+2 theme engine
gtkdialog-0.8.3_4                            A small utility for fast and easy GUI building
gtkimageview-1.6.4_1                         A widget that provides a zoomable and panable view of a GdkPixbuf
gtkmm-3.22.2_1                               C++ bindings for The GTK+ toolkit (v2)
gtkmm2-2.24.5_2                              C++ bindings for The GTK+ toolkit (v2)
gtksourceview-3.24.6_1                       Text widget that extends GTK+3 GtkTextView widget
and some others

xfce4-4.12.0_6
```

```
$ spacefm --version
spacefm 1.0.5
GTK2 UDEV INOTIFY DESKTOP SNOTIFY
```

Didn't change the shortcuts.  It doesn't work neither with keyboard shortcuts, nor using the mouse.

Starting `spacefm` from the command line returns:
```
$ spacefm

(spacefm:25073): SpaceFM-WARNING **: No root settings found in /etc/spacefm/  Setting a root editor in Preferences should remove this warning on startup.   Otherwise commands run as root may present a security risk.
special mount changed: encfs (0:43) on /home/lupe/Db_claro

(spacefm:25073): SpaceFM-WARNING **: mime-type application/x-msdownload has no description (comment)
[h264 @ 0x7f24a404ab40] co located POCs unavailable
[h264 @ 0x7f24a404ab40] co located POCs unavailable
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f24a4049c00] decoding for stream 0 failed
[h264 @ 0x7f24a404a5c0] co located POCs unavailable
[h264 @ 0x7f24a404a5c0] co located POCs unavailable
```
Did a `fusermount -u /home/lupe/Db_claro`, tried again, same problem.

Tried spacefm-ng as well, but the problem remains, so went back to spacefm.

Started spacefm as root but the paste option is dimmed as well.

Can record my desktop if you want.

**Comment by IgnorantGuru** [comment]
Thanks.  A few questions to narrow it down...

If you right-click on a file and select Copy, then put the cursor in the pathbar and select Paste, is the pathname of the file pasted into the pathbar?  Or you can use a text editor or another FM to test the paste.  iow, does it appear Copy is placing files on the clipboard?

Is Delete in the right-click menu also always disabled, or is it only disabled in directories where you have no write access?

jfyi, SpaceFM tests for write access [here](https://github.com/IgnorantGuru/spacefm/blob/24f118d60c5370489b94795ed0a58aa4c799d5aa/src/ptk/ptk-file-menu.c#L769).  That method dates back all the way and there has never been a report like this, so if it is due to write access permissions, something unusual must be involved, perhaps a build or library problem.

You might also try starting with a fresh test config, just to eliminate a configuration issue:

    killall spacefm
    spacefm -c /tmp/spacefm-test

**Comment by lpvm** [comment]
Ok, let's narrow it down.   Tried `spacefm` in my old laptop also using VoidLinux and it works fine.  Although it has much less sotfware installed.

After `Copy`, can `paste` its path into the pathbar and into some text editor.

`Delete` is enabled.
```
$ touch TTT/aa
$ chmod 400 TTT/aa 
$ ls -la TTT/
-r--------   1 lupe lupe     0 fev 25 12:57 aa
```

Even so, `spacefm` deletes the file after asking for confirmation.  I think that delete is working as intended.

The behavior is the same even when starting with a fresh test config.

**Comment by lpvm** [comment]
Just to say that I started a different Xorg session with `$ startx -- :1` that initializes icewm but the strange behavior is the same.

**Comment by IgnorantGuru** [comment]
Thanks.  One more question: Are Actions|Paste Target and Actions|Paste Link also always disabled like Paste is?

I'll schedule this for a walk through the code.  It doesn't sound like it's an access issue, so sounds like either an issue with how the clipboard is read, which would be odd since SpaceFM copied to it, or some glitch with how that menu item is building.

Paste Target can be used as an approximate replacement for Paste.  You can also import my [IG Paste Into](https://github.com/IgnorantGuru/spacefm-plugins/wiki#wiki-ig-paste-into) plugin and use that to replace Paste in the menu for now.  It's functionally almost the same.  Just right-click on a menu item near Paste, select New|Import|URL, and paste in [this link](https://raw.github.com/IgnorantGuru/spacefm-plugins/master/ig-paste-into/pkg/IG-Paste-Into.spacefm-plugin.tar.gz).  Then set a key shortcut as Ctrl+V.

**Comment by lpvm** [comment]
I include a video that shows what's happening.
[paste_problems_spacefm.ogv.zip](https://github.com/IgnorantGuru/spacefm/files/1759971/paste_problems_spacefm.ogv.zip)

I'll try the workaround you mention.

**Comment by ncmprhnsbl** [comment]
what is that gtk theme?

**Comment by lpvm** [comment]
It's vertex-light.

**Comment by ncmprhnsbl** [comment]
ok.. i asked because sometimes gtk themes can cause problems..
but the vertex family is pretty good in that regard..
this is an odd one, i have been using spacefm on Void since 2015 with zero problems..

**Comment by IgnorantGuru** [comment]
Are Actions|Paste Target and Actions|Paste Link also always disabled like Paste is?

**Comment by lpvm** [comment]
Well, in a second look, maybe `IG Paste Into` is not working fine.  Tell me if what I'm doing is the correct procedure.  In the first pane, I copy a file.  Move to the second (on the right), choose a directory and then `Extras | Paste Into`.  Is this the way to do it?  What happens now (maybe I was not so attentive before), is that the file is not pasted, but the directory on this second panel changes to the one of the origin of the file (left panel).  The two panels are showing the same directory.

As for the latest question, yes, `Actions | Paste Target` and `Paste Link` are always disabled.

**Comment by IgnorantGuru** [comment]
That is the correct usage of Paste Into, but is not the correct behavior - the plugin script does not change the dir of the panel.  However, when only text is on the clipboard, it is pasted it into the pathbar, which is probably causing the dir change.  You probably need to uncheck option Ignore Context/Show All on the Context tab of a menu item, then you'll see Paste Into is also disabled due to no files on the clipboard.

Given your answers, it appears that detection of files on the clipboard is not working correctly on your system, which is inexplicable.  Given that this has never arisen before, this may not indicate a problem in SpaceFM's code, but a problem with the clipboard functions on your system, or with GTK/GDK, for whatever reason.

Personally, I would uninstall and try building alpha using the net installer, as a rebuild might correct it if there was a package/library problem on Void.

**Comment by IgnorantGuru** [comment]
Sounds like Parcellite has an intermittent bug which interferes with normal use of the clipboard.  SpaceFM's use of the copy files functions is fairly routine so not much to go wrong there, and compatibility has been good.  I'm not likely to investigate this unless SpaceFM's use of the clipboard is shown to be out of spec.  Thanks for the followup.

Feel free to post below any additional information related to this issue.
